### ISSUE TITLE
Commitment: 73 Merge Requests, 115 Issues, 154 contributors

### ISSUE THREAD

**Issue by LongLiveCHIEF** [puppetlabs/puppetlabs-docker#10]
[garethr/docker](https://github.com/garethr/garethr-docker), previously the upstream source of the the internal `docker_platform` resource in puppet, was last released in July of 2016. Since that time, the community of users have [literally begged](https://github.com/garethr/garethr-docker/issues/699) for support. They've even submitted over 70 Merge Requests to fix the glaring issues that make this module literally unusable unless you're using legacy docker and EoL version of puppet.

There have also been over [150 contributors](https://github.com/garethr/garethr-docker/graphs/contributors) that have participated in the current state of this module. 

I realize the intent of bringing this module here wasn't to bring baggage from its history, but between the persistent absence of a response to any of the issues or MR's, in addition to getting rid of the badge acknowledgement of previous contributors in the history, this sends a message.

Can you please help us make sure we get the right message? Please provide answers to the following questions:
- Does the creation of this module signify a commitment from puppetlabs to actively maintain this module?
- Would it be possible for you take the most recent commits from this project and rebase them onto the commit history from garethr/docker?
- Do you have plans to address or migrate Issues/PR's from garethr/docker to this module

Many of us have worked hard to make this module better, and we're willing to work with folks from puppetlabs wherever they ask us to. All we're ask for is two-way communication.

Thank you

**Comment by scotty-c** [comment]
To answer this first question, Puppet now has full time staff working on this module. So me and the team will be more than happy to work with the anyone who has interest in this module. I am personally on the Puppet community slack (scottyc).

We are not looking at rebasing gareth's module. All development will now be done here.

Also we are not migrating any issues, in saying that we are addressing the major concerns raised by the community 

I hope that clears up any concerns you have

**Comment by LongLiveCHIEF** [comment]
I doesn't clear up _all_ the concerns, but it clears most of them, and the important ones at that. I for one am excited to hear this message, and will be happy to collaborate on improving the module.
