### ISSUE TITLE
Pdk update

### ISSUE THREAD

**Issue by mterzo** [puppetlabs/puppetlabs-docker#104]
This module was created before the release of the PDK, are there any plans for moving this to using the PDK?

**Comment by scotty-c** [comment]
@mterzo we have already migrated the module to use PDK. What features are you missing?

**Comment by mterzo** [comment]
Spec and rubocop tasks are not being executed in the ci pipelines.  Also missing the rubocop configurations.

**Comment by davejrt** [comment]
@mterzo I'll chase this up and get back to you with a rough timeline.

**Comment by mterzo** [comment]
I saw you added the spec task to rake.   There are lots of fixes to conform to rubocop.

**Comment by scotty-c** [comment]
@mterzo we will add a ticket in our backlog to look at the rubocop validation

**Comment by mterzo** [comment]
I have most of the work done already.  Didn’t know if there was a reason you weren’t already doing it.

**Comment by scotty-c** [comment]
closing due to #120
