### ISSUE TITLE
 validate_re(): input needs to be a String

### ISSUE THREAD

**Issue by vinayakbhat24** [puppetlabs/puppetlabs-docker#106]
Hi,

When I try to include docker in my init.pp I will get the following error:

     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, validate_re(): input needs to be a String, not a NilClass at C:/Users/vibh/WORKDIR/my_docker/spec/fixtures/modules/docker/manifests/init.pp

Stdlib Version :4.24.0
Puppet version:  4.10.9

Thanks,

**Comment by davejrt** [comment]
Can I get a bit more information like OS, module version etc. 

Which line is it failing on?

**Comment by scotty-c** [comment]
@vinayakbhat24 can share your code with us, how are you including the Docker class
