### ISSUE TITLE
Update Repo/Install on Centos to support new Docker versions

### ISSUE THREAD

**Issue by bstucker** [puppetlabs/puppetlabs-docker#11]
Update install method on Centos to support latest versions of Docker CE past 17.0.5

Example install instructions for new repo is https://docs.docker.com/engine/installation/linux/docker-ce/centos/#install-using-the-repository

Not sure if its worth adding logic at the same time to add option for the edge/stable/test release

EDIT:  Same issue from garethr source https://github.com/garethr/garethr-docker/issues/676

**Comment by scotty-c** [comment]
This is top of our list to fix in the next release.

**Comment by davejrt** [comment]
This is actively being worked on in the current sprint

**Comment by scotty-c** [comment]
We are also updating the Ubuntu/Debian repos as part of this issue as well.

**Comment by scotty-c** [comment]
There is a PR up for review for this issue #31

**Comment by scotty-c** [comment]
PR #31 is now in master, we have some other changes we would like to add before the next release.
So it will be published on the Forge with that release.

That release will be next week sometime
