### ISSUE TITLE
Failed to fetch https://download.docker.com/linux/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'stable/binary-i386/Packages'

### ISSUE THREAD

**Issue by RussellMcOrmond** [puppetlabs/puppetlabs-docker#113]
The /etc/apt/sources.list.d/docker.list which this module creates is simple:

```
root@toma:~# cat /etc/apt/sources.list.d/docker.list 
# This file is managed by Puppet. DO NOT EDIT.
# docker
deb https://download.docker.com/linux/ubuntu trusty stable
```

The problem is that there is no empty i386 list - there wouldn't be an i386 docker, but Apt still looks even though the arch is x86_64

If I add [arch=amd64] to force the architecture, all works well.

`deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable`

This reference to the forced arch= is mentioned in the docs.
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#set-up-the-repository

Is there any chance this could be added, based of course on the actual architecture detected?

At the moment I need to run a 'sed' script to manually modify the file any time I want to update packages, as apt fails looking for the missing i386 repository for Trusty.

**Comment by davejrt** [comment]
fixed in PR #115
