### ISSUE TITLE
Huge module size in 1.0.4

### ISSUE THREAD

**Issue by htj** [puppetlabs/puppetlabs-docker#117]
The 1.0.4 release grew a lot:

.../dist/puppet-modules$ ls -lh *.tar.gz
-rw-r--r--  1 htj  staff    67K Jan 12 14:26 puppetlabs-docker-1.0.2.tar.gz
-rw-r--r--@ 1 htj  staff   1.7M Jan 15 14:29 puppetlabs-docker-1.0.4.tar.gz

Looks like it includes several other modules:

$ ls puppetlabs-docker-1.0.4/spec/fixtures/modules/
apt    docker epel   stdlib

$ du -hs puppetlabs-docker-1.0.4/spec/fixtures/modules/
4.5M	puppetlabs-docker-1.0.4/spec/fixtures/modules/

Is this intentional?

**Comment by davejrt** [comment]
I'll get this fixed in 1.0.5

**Comment by scotty-c** [comment]
closing due being fixed in release 1.0.5
