### ISSUE TITLE
Support for network in docker::run

### ISSUE THREAD

**Issue by htj** [puppetlabs/puppetlabs-docker#118]
Hi

After getting support for docker::network in 1.0.4, it would be nice if one could do network in docker::run instead of using extra_parameters, e.g.:

docker::run { 'whatever':
  image     => 'whatever:1.2.3.',
  network  => [ 'whatever-internal' ]
}

**Comment by scotty-c** [comment]
@htj you could always pass network in the extra params resource `extra_parameters => [ '--network=whatever-internal']`. Due to networking also being needed by swarm we needed to externalise the class. So this would the suggested solution.

**Comment by htj** [comment]
I'm using extra_parameters right now, and it works. While extra_parameters is very nice to have in these situations, it does feel like a step to close to writing scripts. Having an external class for networking is fine, but it is such a common thing to have that a key in docker run would be warranted imho.

**Comment by scotty-c** [comment]
@htj More than happy to look at a PR for this. Internally this is not something we will be looking at in the next few releases.

**Comment by davejrt** [comment]
Closing as this isn't on the puppet roadmap. Please submit a PR if you'd like this implemented as mentioned above
