### ISSUE TITLE
Systemd escaping

### ISSUE THREAD

**Issue by olivierHa** [puppetlabs/puppetlabs-docker#124]
Hello, 

As already reported in the "Issues " of gareth-docker ([#647](https://github.com/garethr/garethr-docker/issues/647) or [#432](https://github.com/garethr/garethr-docker/issues/432) there is an issue with complex run commands under systemd.

I ran into the same issue, while adding JVM_ARGS to a docker container,  for example
JVM_ARGS='-Xms2048m -Xmx2048m -XX:MaxDirectMemorySize=1g`

The patch provided in the previous issue, solves this issue.

**Comment by scotty-c** [comment]
closing due to #125 being merged
