### ISSUE TITLE
When using the RedHat distro of docker, docker_group is `dockerroot`

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/puppetlabs-docker#133]
Logic to fix this used to exist: https://github.com/puppetlabs/puppetlabs-docker/blob/defb08ff6238f0d014aef487f79d686e278a5d1b/manifests/params.pp#L212
but was removed.

Now it just assumes `docker` is correct, which it is not when `use_upstream_package_source` is set to false.

**Comment by davejrt** [comment]
Fixed in PR #134
