### ISSUE TITLE
error while resolving custom fact

### ISSUE THREAD

**Issue by HanzzM** [puppetlabs/puppetlabs-docker#137]
Error: Facter: error while resolving custom fact "docker_client_version": undefined method `[]' for nil:NilClass
Error: Facter: error while resolving custom fact "docker_server_version": undefined method `[]' for nil:NilClass

**Comment by MWilsonPuppet** [comment]
Hi @HanzzM Could you please provide some more information so I can take a look at this:
The version of the module you are using
The OS
The version of docker and puppet that you are using and a sample of your manifest  you are trying to run
thanks
Mark.

**Comment by HanzzM** [comment]
Version of the module is "1.0.5"
OS = RHEL7.4

[root@slid25020 ~]# puppet master --version
4.10.9
[root@slid25020 ~]# puppet agent --version
4.10.9

[root@slid25020 ~]# docker --version
Docker version 17.06.2-ee-6, build e75fdb8

 ```
# Docker EE
  class { 'docker':
    docker_ee                      => true,
    use_upstream_package_source    => false,
    repo_opt                       => '--enablerepo=rhel-7-server-extras-rpms',
    ip_forward                     => true,
    iptables                       => true,
    ip_masq                        => true,
    selinux_enabled                => 'false',
    log_level                      => 'warn',
    storage_driver                 => 'overlay2',
    overlay2_override_kernel_check => true,
    proxy                          => 'http://proxy.example.coml:80',
    no_proxy                       => 'localhost, .local',
    require                        => Mount['/var/lib/docker'],
    notify                         => Exec['restorecon_docker_ee'],
  }
```


```
# puppet agent --test
Info: Using configured environment 'research'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom fact "docker_client_version": undefined method `[]' for nil:NilClass
Error: Facter: error while resolving custom fact "docker_server_version": undefined method `[]' for nil:NilClass
Info: Caching catalog for slid25020.unix.bank.local
Info: Applying configuration version '1518177592'
Notice: Applied catalog in 17.53 seconds

```

**Comment by HanzzM** [comment]
BTW, no problems with version "1.0.4"

**Comment by HanzzM** [comment]
The problem is solved.
There was a conflict with the by ourselves written facter "docker-version".
We have removed our facter.
