### ISSUE TITLE
package_name parameter no longer exists

### ISSUE THREAD

**Issue by jaxxstorm** [puppetlabs/puppetlabs-docker#140]
The `package_name` parameter seems to have vanished, and now there's some regex logic which detects the version number and then seems to make a decision about which package to install.

It should be possible to explicitly set the `package_name` and override the autodetects where possible.

**Comment by davejrt** [comment]
Hi

You can set the package name via the `docker_engine_package_name` or the `docker_ce_package_name` depending on which version of the engine you're using. 

Can you please provide more detail about which version you're using, and how?

**Comment by davejrt** [comment]
Closing as a valid solution is available in the module

**Comment by jaxxstorm** [comment]
@davejrt I've set the docker_ce_package_name parameter, but because of the way the logic is defined, it's still installing the docker-engine package. I had to set `docker_engine_package_name` to the name of the docker ce package to get it working

**Comment by davejrt** [comment]
Assuming you want the ce package, can you show me your manifest and a log file? The following executes as I'd expect it to

```
node default {

  class {'docker':
    docker_ce_package_name => 'testing',
  }

}
```

```
==> node-01: Error: /Stage[main]/Docker::Install/Package[docker]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install testing' returned 100: Reading package lists...
==> node-01: Building dependency tree...
==> node-01: Reading state information...
==> node-01: E: Unable to locate package testing
```
