### ISSUE TITLE
Error in `docker` fact

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/puppetlabs-docker#141]
On CentOS 7 and Docker 1.12.6, I receive the following error:

```
Error: Facter: error while resolving custom fact "docker": A JSON text must at least contain two octets!
```

I tried running the command in the fact `exec` section and got this error:
```
[root@server01 ~]# docker info --format '{{json .}}'
flag provided but not defined: --format
See '/usr/bin/docker-current info --help'.
[root@server01 ~]# 
```

**Comment by davejrt** [comment]
I'll bring this up internally and get someone to look at confining the fact to engine 1.13 and later.

**Comment by jeefberkey** [comment]
It only results in a warning when puppet runs, not a failure or anything
