### ISSUE TITLE
Boolean vs String for dm_use_deferred_removal / dm_use_deferred_deletion

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-docker#143]
Please see the comments on this PR:
https://github.com/puppetlabs/puppetlabs-docker/pull/99

The typing for dm_use_deferred_removal and dm_use_deferred_deletion was set to String, whereas we had assumed previously that those were Booleans (due to having true/false as options).  I'm assuming the String type was used because the defaults were set to undef (probably should have been false).

Is the String type desired, in which case we'll have to update our settings to quote true/false (which requires a Lint override), or was this an oversight and they should be set to Boolean?

**Comment by sheenaajay** [comment]
thanks @esalberg @dol for valuable comment.Will get the fix soon for the following variables and update the spec tests accordingly.

**Comment by sheenaajay** [comment]
Thank you.The PR is ready with the fix https://github.com/puppetlabs/puppetlabs-docker/pull/145

**Comment by sheenaajay** [comment]
dm_use_deferred_removal and dm_use_deferred_deletion use the data type Boolean in this PR

**Comment by davejrt** [comment]
fixed in PR #145
