### ISSUE TITLE
Wrong systemd access level on RHEL

### ISSUE THREAD

**Issue by Thorndike** [puppetlabs/puppetlabs-docker#151]
I am using docker plugin 1.0.4 on RHEL 7.4. In /var/log/messages the system is complaining about incorrect access levels to the puppet generated service files. 

Feb  8 08:58:23 rhscpm015 systemd[1]: Configuration file /etc/systemd/system/docker-verzeichnisMock_inst1.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.

Pleas change the file attributes to make them world-accessible.

**Comment by davejrt** [comment]
I don't see this as being an actual issue, or presently any problem in functionality of docker or the module.
