### ISSUE TITLE
socket_group no longer undef by default

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-docker#152]
This PR changed the socket_group default from undef (as documented in readme and init.pp) to a value.
https://github.com/puppetlabs/puppetlabs-docker/pull/107

When I try to upgrade the Docker module, it means that /etc/sysconfig/docker is changing and it will restart the Docker daemon across my hosts.  In theory, this shouldn't matter, but in practice, it's a big enough hassle for us that I'm forking the module to work around it.

Is there a way that the default can be changed back to undef, at least for RedHat with use_upstream_package_source set to false?

(Weirdly, I am seeing -G docker, even though based on params, I should be seeing -G dockerroot for my config.  I'll dig into that, but regardless, I can't unset it with the current code.)

**Comment by scotty-c** [comment]
@esalberg The containerd shim should keep the containers running even if the daemon is restarted.
We have had multiple other community members asking for the change #98

**Comment by esalberg** [comment]
It does if you have --live-restore in the docker sysconfig, but otherwise, from my testing, it does not.

We are working to roll out --live-restore anyway, so I'll do a short term fork to workaround this issue, but it does seem like a breaking change.  I don't really see why the other community members couldn't just override the undef.

At the very least, could the documentation be updated so that it's not incorrect?  I'd prefer not to put in a PR to document a change I didn't want. :)

**Comment by davejrt** [comment]
Documentation updated in PR #158
