### ISSUE TITLE
docker-compose pull support

### ISSUE THREAD

**Issue by otdevops** [puppetlabs/puppetlabs-docker#155]
In a development environment, developers don't want to constantly change dev tags.  We are using a static dev tag on our images.  Puppet will not pull this updated image if it already exists.

Consider adding docker-compose pull ability to pull existing tags based on the newest images.

**Comment by davejrt** [comment]
Hi

At the moment this isn't a priority for us at the moment, as there are alternate ways to tag your images that would be a better practise, even in dev. Having said that, we're happy to look at community PRs to solve the issue.
