### ISSUE TITLE
docker::compose creates 0 byte /usr/local/bin/docker-compose-1.9.0

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/puppetlabs-docker#159]
If https://github.com/puppetlabs/puppetlabs-docker/blob/9ac570b3a1a3cf1a5f45a8a844b31f3413761401/manifests/compose.pp#L46 fails, it creates a 0 byte file and the download is not reattempted on the next puppet run.

Instead of redirecting stdout to a file, better to use curl's `-o` option?

**Comment by alexjfisher** [comment]
?? *if* the download fails you get a 0 byte file. Maybe your internet was temporarily down, your proxy was broken or even GitHub is temporarily unavailable. Curl fails but the exec leaves an empty file behind due to using redirection of stdout.

**Comment by scotty-c** [comment]
@alexjfisher we are using the curl command that is out of Docker's official install docs https://docs.docker.com/compose/install/#prerequisites

**Comment by alexjfisher** [comment]
@scotty-c Hi!  If you're manually running the command and it fails, you can rerun it.  The issue is that puppet won't.  It really isn't a massive deal, but equally, it's trivial to fix.  I was going to submit a simple PR.

I don't think the exact syntax in the docs is relevant, but... they were updated in August in this commit https://github.com/docker/docker.github.io/commit/4b851679759b334c58d8985ea216d62356f65699#diff-4286581200875e50bd6c1a0dfa891337R117
