### ISSUE TITLE
docker-run.erb has service name hard-coded to docker.service

### ISSUE THREAD

**Issue by robert4man** [puppetlabs/puppetlabs-docker#16]
This causes problems if/when setting package_name => 'docker-latest' and service_name  => 'docker-latest'. An easy workaround is to set restart => 'always' in docker::run_instance::instance, but I would like to use systemd restart specific docker instances without having to completely restart docker.

**Comment by scotty-c** [comment]
Closing due to #17 being merged. Thanks for your contribution.
