### ISSUE TITLE
Readme.md files required to be add repo_opt for installation of docker on rhel based system

### ISSUE THREAD

**Issue by thatsk** [puppetlabs/puppetlabs-docker#161]
On To use CE class packages:-
```
class { 'docker':
  use_upstream_package_source => false,
  docker_package_ce_name      => 'docker-ce',
}
```
it should be look like this:
```
class { 'docker':
  use_upstream_package_source => false,
  repo_opt => ''
  docker_package_ce_name      => 'docker-ce',
}
```

**Comment by davejrt** [comment]
You don't need to force the package name in this unless you're using a non-default. Depending on the version you'll end up with either docker-ce or docker-engine. The addition of an empty repo_opt is valid and it may be worth putting in logic to unset this of the `use_upsteam_package_source` is set to false and I don't see if being valid in any other scenario.

**Comment by thatsk** [comment]
If we are not adding that option by default it can picking up from extras
repository which is not correct. So how you workaround it.

**Comment by davejrt** [comment]
The following is a valid work around with the module in its current state, what you have proposed is technically correct but as I mentioned, you don't need to force the package name:

```
class { 'docker':
  use_upstream_package_source => false,
  repo_opt => ''
```

**Comment by thatsk** [comment]
I agree but on cientos If I want to install what's you suggest to puppet
client user to use in hiera

**Comment by davejrt** [comment]
Whether or not you're using hiera, it's irrelevant. The values remain the same, the hiera would just look like this:

If you're seeing an error with the config that I've supplied I'm happy to review the log. 
```
docker::use_upstream_package_source: false
docker::repo_opt: ' ' 
```

**Comment by thatsk** [comment]
To use the CE packages

```puppet
class { 'docker':
  use_upstream_package_source => false,
  docker_package_ce_name      => 'docker-ce',
}
```
This need to be corrected with
```puppet
class { 'docker':
  use_upstream_package_source => false,
  docker::repo_opt: ' ' 
  docker_package_ce_name      => 'docker-ce',
}
```

**Comment by davejrt** [comment]
The repo_opt param has been added to the readme in PR #174
