### ISSUE TITLE
Syntax error in file ./spec/defines/stack.rb

### ISSUE THREAD

**Issue by mick1627** [puppetlabs/puppetlabs-docker#163]
Hi

We have a script to check the module syntax before pushing the file on the puppetmaster.
There is a syntax error in the file stack.rb

ruby -c ./spec/defines/stack.rb
./spec/defines/stack.rb:29: syntax error, unexpected end-of-input, expecting keyword_end

**Comment by scotty-c** [comment]
fixed in #164
