### ISSUE TITLE
Docker registry is never called after first run

### ISSUE THREAD

**Issue by sigsegv11** [puppetlabs/puppetlabs-docker#167]
I am encountering issues when docker login is run and a network hiccup occurs (some people love their firewall). The receipt is created either way even though no login has happened. And because of this every pull will fail evens after the network hiccup. 

My proposed solution is to perform the login each time but to surpress the output using unless.

For example:

```
  exec { "${title} auth":
    environment => $auth_environment,
    command     => $auth_cmd,
    user        => $local_user,
    cwd         => '/root',
    path        => ['/bin', '/usr/bin'],
    timeout     => 0,
    unless      => $auth_cmd,
#    refreshonly => $receipt,
  }

```
Pro: we see if the login fails Now in that case it will only show up if something goes wrong.
Con: We dont see the initial (and subsequent logins)

Any ideas on this?

Or add the possibility to just surpress the login in that case both options receipt and continuously login can live together?

**Comment by davejrt** [comment]
Hi @sigsegv11 apologies for the delay in getting back to you. 

I think if this is an issue in your environment you can set receipt to false and you'll get the old functionality back without having to change any code. I'm not opposed to this code being changed, if we can get the code to a point where it doesn't create the receipt if the login fails..then that satisfies the requirements. 

This wouldn't be a priority for us at the moment, given we can currently turn off the receipt and ensure the login is checked each time if it tails, but I'm happy to review a community PR that addresses it.
