### ISSUE TITLE
Syntax error with fresh install

### ISSUE THREAD

**Issue by OneBadSanta** [puppetlabs/puppetlabs-docker#170]
I'm attempting to install a fresh system and receive the following error after running the commands below.

Error: Syntax error at 'Optional'; expected ')' at /etc/puppet/modules/docker/manifests/init.pp:356 on node ubuntu-xenial.example.com

To get to this error, I did the following.

~: vagrant init ubuntu/xenial64
~: vagrant up
~: vagrant ssh

~$: wget http://apt.puppetlabs.com/puppet-release-xenial.deb -P /tmp/
~$: sudo dpkg -i /tmp/puppet-release-xenial.deb
~$: sudo apt update
~$: sudo apt install -y puppet
~$: sudo puppet module install puppetlabs-docker --version 1.0.5
~$: echo "include 'docker'" > test.pp
~$: sudo puppet apply test.pp

I replaced the contents with typical puppet manifest stuff like the example below and it works fine.

exec { 'apt-update': command => '/usr/bin/apt-get update' }
package { 'htop': require => Exec['apt-update'], ensure => installed, }

Am I missing something or misunderstanding the usage of this module?

**Comment by scotty-c** [comment]
@OneBadSanta do you have stdlib installed? 
https://forge.puppet.com/puppetlabs/stdlib

If that is installed what version of Puppet are you running?

**Comment by OneBadSanta** [comment]
@scotty-c Thanks for the quick reply. 

Yes. stflib was installed when I installed puppetlabs-docker

/etc/puppet/modules
└─┬ puppetlabs-docker (v1.0.5)
  ├── puppetlabs-apt (v4.5.1)
  ├── puppetlabs-stdlib (v4.24.0)
  └── puppetlabs-translate (v1.0.0)

These are the puppet versions installed

vagrant@ubuntu-xenial:~$ sudo dpkg -l |grep puppet*
ii  puppet . 3.8.5-2ubuntu0.1 . all . configuration management system, agent
ii  puppet-common . 3.8.5-2ubuntu0.1 .  all . configuration management system
ii  puppet-release . 1.0.0-1xenial . all . Release packages for the Puppet repository

**Comment by scotty-c** [comment]
@OneBadSanta can you try getting Puppet from this repo
`wget https://apt.puppetlabs.com/puppet5-release-xenial.deb && sudo dpkg -i puppet5-release-xenial.deb`

**Comment by OneBadSanta** [comment]
I just tried your suggestion with a new fresh ubuntu xenial box. It installs the same version modules and has the same error output from the apply command. Here's the packages installed

ii  puppet                           3.8.5-2ubuntu0.1                           all          configuration management system, agent
ii  puppet-common                    3.8.5-2ubuntu0.1                           all          configuration management system
ii  puppet5-release                  5.0.0-1xenial                              all          Release packages for the Puppet5 repository

Forgive me if it's some dumb issue on my end. I haven't used puppet for a few years and I barely picked it back up today to use it with Docker :)

**Comment by davejrt** [comment]
start from scratch, and run `apt-get -y install puppet-agent` using the the deb that @scotty-c gave you. You're still trying to run puppet 3.8.5 which is why it doesn't work.

**Comment by OneBadSanta** [comment]
@scotty-c @davejrt 

Yes!! That was totally it. The puppet-agent package works properly and installs the newer version. I was running sudo apt install puppet instead. Sorry for wasting yours guys time. I knew it had to be something dumb on my end. Thanks for being awesome :)

**Comment by davejrt** [comment]
@OneBadSanta no worries, glad we could help
