### ISSUE TITLE
docker-compose.yml version evaluation issue in Docker/Compose

### ISSUE THREAD

**Issue by rgfdic** [puppetlabs/puppetlabs-docker#172]
I am receiving the error message listed below when using any version inside the docker-compose.yml file because the regex code to be evaluated in "docker/lib/puppet/provider/docker_compose/ruby.rb" is not correct. 

**Error: docker-compose.yml]: Could not evaluate: Unsupported docker compose file syntax version "2"!**

The current value is: **when %r{^2(\.0)?$/, /^3(\.[0-2])?$}**
This will not work.

One correct option is: **when /^2(\.0)?$/, /^3(\.[0-2])?$/**

**Comment by davejrt** [comment]
Can you please provide an example of a compose file producing the error?

**Comment by rgfdic** [comment]
Davejrt,

Here it is:

--- Start of compose file content
version: '2'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '8080:8080'
--- End of compose file content

Puppet Enterprise version 2017.3.2
Puppet Agent version 5.3.3
Official docker module version 1.0.5

**Comment by davejrt** [comment]
I'm afraid I can't replicate the error, and we actually test this scenario in our acceptance tests.

[https://github.com/puppetlabs/puppetlabs-docker/blob/122a2c7317efdc2d77fa0ab6352de0ebc21126cd/spec/spec_helper_acceptance.rb#L52](url)

**Comment by sigsegv11** [comment]
Hi this is already fixed in the master see #157

**Comment by scotty-c** [comment]
closing due to fix in #157 and further changes in #210
