### ISSUE TITLE
Changelog on the Puppet Forge is from garethr-docker v5.3

### ISSUE THREAD

**Issue by stefanlasiewski** [puppetlabs/puppetlabs-docker#18]
The [puppetlabs/docker changelog](https://forge.puppet.com/puppetlabs/docker/changelog) is out of date, and doesn't show any notes newer than "2016-07-13 - Version 5.3". I imagine that's out of date. :)

See the attached screenshot:

![image](https://user-images.githubusercontent.com/142752/31564783-2ba4357a-b019-11e7-97c5-68c6c565548a.png)

**Comment by dol** [comment]
I'm also interested in the changelog. I'd like to switch over to the 'puppetlabs/docker' v1.0.0 from 5.3.0. But without a proper update/changelog guide this might be a bit risky.

**Comment by scotty-c** [comment]
The changelog has been updated to represent this modules and its new home. I am closing this issue now. Please re open it if you have any other questions around the changelog
