### ISSUE TITLE
1.0.6 release?

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-docker#192]
Hi -- is a new release coming pretty soon? In particular, I really need this fix:

https://github.com/puppetlabs/puppetlabs-docker/pull/168

It looks like it's been pushed into the master branch, but a release hasn't been cut since 1.0.5 on Jan 30th.

Thanks,
John

**Comment by vrmerlin** [comment]
Actually, I've figured out how to grab from the master branch with my Puppetfile, so I can do that for now. But... I'm having a problem with the #168 fix. I'll create a different issue for that... 

I'd still be curious to know the timeframe for the 1.0.6 release.

**Comment by davejrt** [comment]
@vrmerlin within the next 24 hours. You can also contact us on the community slack as well.

**Comment by davejrt** [comment]
v.1.1.0 has been released to the forge
