### ISSUE TITLE
Problem getting RedHat extras repo on workstations

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-docker#193]
## What you expected to happen?

I've grabbed the master branch with fix #168. However, when I tried it, it still doesn't work on my system.

## What happened?

I get the error:

`Error: Execution of '/bin/yum -d 0 -e 0 -y --enablerepo=rhel-7-server-extras-rpms install docker-ce' returned 1: Error getting repository data for rhel-7-server-extras-rpms, repository not found
`

## How to reproduce it?

My system is a workstation, not a server. The fix for #168 seems to only work on servers. Try doing a docker installation on a RedHat workstation to reproduce.

## Anything else we need to know?

My yum list of repos contains the following:

`!rhel-7-workstation-extras-rpms/x86_64                                                          Red Hat Enterprise Linux 7 Workstation - Extras (RPMs)                                     enabled:     34`

## Versions:

```
$ puppet --version
5.3.5
$ docker version
(doesn't get installed)
$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "Maipo",
    description => "Red Hat Enterprise Linux Workstation release 7.4 (Maipo)",
    id => "RedHatEnterpriseWorkstation",
    release => {
      full => "7.4",
      major => "7",
      minor => "4"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.4",
    major => "7",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}
$ puppet module list
/etc/puppetlabs/code/environments/production/modules (no modules installed)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)

```

**Comment by davejrt** [comment]
@vrmerlin the module does not currently support workstations. You can override `repo_opt` param in your node definition to change the repo name in this case

**Comment by vrmerlin** [comment]
I guess I'm not sure what you mean by how i would override repo_opt in my node definition. Is there an example someplace?

I'll play around with putting a PR together, but I'm not sure yet how to tell the difference between a workstation and a server (e.g. "facter" doesn't contain the word "workstation" anywhere).

**Comment by davejrt** [comment]
In the [setup](https://github.com/puppetlabs/puppetlabs-docker/blob/master/README.md#setup) portion of the readme it provides an example of how to override the default repo options. 

In your case I would suspect that something like this would do the trick

```puppet
node docker_host {

  class { 'docker':
    repo_opt => 'rhel-7-workstation-extras-rpms',
 }
```

**Comment by vrmerlin** [comment]
Close! Here's what worked:

    repo_opt => '--enablerepo=rhel-7-workstation-extras-rpms',


Thanks!
