### ISSUE TITLE
Broken systemd service definition

### ISSUE THREAD

**Issue by slawekgl79** [puppetlabs/puppetlabs-docker#209]
## What you expected to happen?
After docker module update (1.0.4 -> 1.1.0) containers can be still managed by puppet

## What happened?
After module update (1.0.4 -> 1.1.0) the container can not be started

## How to reproduce it?
run gitlab in container with following configuration:

  docker::run { 'gitserver':
    image             => 'gitlab/gitlab-ce:1.0.0',
    hostname          => 'gitserver.example.com',
    ports             => ['443:443', '2226:22'],
    volumes           => ['/opt/gitlab/config:/etc/gitlab', '/opt/gitlab/logs:/var/log/gitlab', '/opt/gitlab/data:/var/opt/gitlab'],
   env               => 'GITLAB_OMNIBUS_CONFIG="external_url \\'https://gitserver.example.com\'; gitlab_rails[\\'gitlab_shell_ssh_port\\'] = 2226"',
    extra_parameters  => [ '--restart=always'],
  }
## Anything else we need to know?
When setting the environment variable with docker::run, it is stored in exclamation marks in the systemd service file of the container. It is not necessary and may brake valid configuration.
Change in lib/puppet/parser/functions/docker_run_flags.rb in line 69 causes the problem.

## Versions:

```

System Debian 9.3 4.9.0-4-amd64

$ puppet --version
5.5.0

$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:54 2017
  OS/Arch:	linux/amd64
  Experimental:	false

$ facter os
{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.3 (stretch)",
    id => "Debian",
    release => {
      full => "9.3",
      major => "9",
      minor => "3"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.3",
    major => "9",
    minor => "3"
  },
  selinux => {
    enabled => false
  }
}

**Comment by scotty-c** [comment]
@slawekgl79 I am looking at your issues now. There seems to be a syntax error in `volumes => ['/opt/gitlab/config:/etc/gitlab', '/opt/gitlab/logs:/var/log/gitlab', '/opt/gitlab/data:/var/opt/gitlab'],
env => 'GITLAB_OMNIBUS_CONFIG="external_url 'gitserver.example.com'; `  Could you please double check this for me ?

**Comment by slawekgl79** [comment]
H @scotty-c, thank you for your reply. I've checked this and can see my error. The editor just cut off the backslashes before apostrophe, and i haven't noticed it. The volume part is correct (in my opinion)

volumes => ['/opt/gitlab/config:/etc/gitlab', '/opt/gitlab/logs:/var/log/gitlab', '/opt/gitlab/data:/var/opt/gitlab'],

and then comes env:

env               => 'GITLAB_OMNIBUS_CONFIG="external_url \\'https://gitserver.example.com\'; gitlab_rails[\\'gitlab_shell_ssh_port\\'] = 2226"',

Before update it worked fine, but after update to 1.1.0 the whole env part is "qouted" in the service file like this:

....
-e "GITLAB_OMNIBUS_CONFIG="external_url 'https://gitserver.example.com'; gitlab_rails['gitlab_shell_ssh_port'] = 2226"" \ 
-p 443:443 \ 
-p 2226:22 \ 
-v /opt/gitlab/config:/etc/gitlab 
....

working version generated by the module 1.0.4 was:
....
-e GITLAB_OMNIBUS_CONFIG="external_url 'https://gitserver.example.com'; gitlab_rails['gitlab_shell_ssh_port'] = 2226" \ 
-p 443:443 \ 
-p 2226:22 \ 
-v /opt/gitlab/config:/etc/gitlab 
....

**Comment by scotty-c** [comment]
@slawekgl79 Thanks for updating the issue. I will test this out in the next 24 hours and update the issue.

**Comment by slawekgl79** [comment]
@scotty-c I can not test your version now, but I'm confident it is working as your test was positive. I will check this approach at next change on our gitserver. Thank you for your time. For me the ticket can be closed.

**Comment by slawekgl79** [comment]
@scotty-c Your solution is working well. Thank you very much, i was able to change to default module version!
