### ISSUE TITLE
systemd service runs always the latest/master image

### ISSUE THREAD

**Issue by koma85** [puppetlabs/puppetlabs-docker#211]
## What you expected to happen?
when I specify a tag for an Image the systemd service (not checked the other) should append the :tag to the script. This does not happen.
## What happened?
The systemd running script is wrong

## How to reproduce it?
place a tag and look for what images is used.

## Anything else we need to know?
Probably just need a patch on the ERB

## Versions:

```
This is not version related.
```

## Logs:
```
This is not visible from logs.
```

**Comment by scotty-c** [comment]
@koma85 can you send through a copy of the systemd file that this is happening on

**Comment by koma85** [comment]
Calling an image that is called centreon_vmware_connector with tag fix-division-by-0

This is the file 

> /etc/systemd/system/multi-user.target.wants/docker-centreon_vmware_connector.service

```
# This file is managed by Puppet and local changes
# may be overwritten

[Unit]
Description=Daemon for centreon_vmware_connector
After=docker.service
Wants=
Requires=docker.service

[Service]
Restart=on-failure
StartLimitInterval=20
StartLimitBurst=5
TimeoutStartSec=0
RestartSec=5
Environment="HOME=/root"
SyslogIdentifier=docker-centreon_vmware_connector
ExecStartPre=-/usr/bin/docker kill centreon_vmware_connector
ExecStartPre=-/usr/bin/docker rm  centreon_vmware_connector

ExecStart=/usr/bin/docker run \
        --net centreon -m 0b --restart=always \
        --name centreon_vmware_connector \
        git.XXXYYZZ.com:8443/containers/centreon-vmware-connector \

ExecStop=-/usr/bin/docker stop --time=0 centreon_vmware_connector
ExecStop=-/usr/bin/docker rm  centreon_vmware_connector

[Install]
WantedBy=multi-user.target
```

should be:
```
# This file is managed by Puppet and local changes
# may be overwritten

[Unit]
Description=Daemon for centreon_vmware_connector
After=docker.service
Wants=
Requires=docker.service

[Service]
Restart=on-failure
StartLimitInterval=20
StartLimitBurst=5
TimeoutStartSec=0
RestartSec=5
Environment="HOME=/root"
SyslogIdentifier=docker-centreon_vmware_connector
ExecStartPre=-/usr/bin/docker kill centreon_vmware_connector
ExecStartPre=-/usr/bin/docker rm  centreon_vmware_connector

ExecStart=/usr/bin/docker run \
        --net centreon -m 0b --restart=always \
        --name centreon_vmware_connector \
        git.XXXYYZZ.com:8443/containers/centreon-vmware-connector:fix-division-by-0 \

ExecStop=-/usr/bin/docker stop --time=0 centreon_vmware_connector
ExecStop=-/usr/bin/docker rm  centreon_vmware_connector

[Install]
WantedBy=multi-user.target
```

**Comment by koma85** [comment]
Didn't wqant to close

**Comment by scotty-c** [comment]
@koma85 Can you send through your `docker::run` code, please

**Comment by scotty-c** [comment]
@koma85 can you send your code that is creating the container, please

**Comment by koma85** [comment]
I've looked into the code and mayne I've found what the problem could be.
declaring the image I don't define a resurce type but only asking for docker to have that image on the server.

```
  docker::image { $docker_image_centreon_connector:
    image_tag => $docker_image_centreon_connector_tag,
  }
```

Then asking docker to run the image withotu specifing the tag runs the first image that could find:
```
  docker::run { 'centreon_vmware_connector':
    image            => $docker_image_centreon_connector,
    restart_service  => true,
    extra_parameters => [ '--restart=always' ],
    net              => $docker_network,
    volumes          => ["${centreon_vmware_config}:${docker_centreon_vmware_conf_bind}"],
    require          => File[$centreon_vmware_config],
  }
```
In my case on the first run I didn't specify any tag so the image downloaded was the **:latest**

After that I've specified an image but having the latest already downloaded docker runt the latest and not the one with the tag I've declared.

To correct this behaviour I need simply to add the tag on the docker image name string:
```
  docker::run { 'centreon_vmware_connector':
    image            => $docker_image_centreon_connector:$docker_image_centreon_connector_tag,
    restart_service  => true,
    extra_parameters => [ '--restart=always' ],
    net              => $docker_network,
    volumes          => ["${centreon_vmware_config}:${docker_centreon_vmware_conf_bind}"],
    require          => File[$centreon_vmware_config],
  }
```

I would suggest at this point to add the `tag =>` flag to the docker::run function.
Looks simpler to implement and less prone to errors or misconfusion.

**Comment by davejrt** [comment]
Closing as the module already replicates the docker cli and recommended behaviour sufficiently. I'll add a note to the readme making it clear that not specifying an image tag, or using latest is a bad practice
