### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by hamon-e** [puppetlabs/puppetlabs-docker#215]
puppet version: 3.6.7
puppet module: 
     puppetlabs-apt (v4.5.1)
     puppetlabs-docker (v1.1.0)
     puppetlabs-stdlib (v4.25.1)
     puppetlabs-translate (v1.0.0)

Hello,
I'm new to puppet so maybe this is a configuration error.

I have this error: ```Apr 07 10:32:47 puppet puppet-master[3111]: Syntax error at 'Optional'; expected ')' at /etc/puppet/modules/docker/manifests/init.pp:367 on node master.service.consul```

My site.pp ``` node 'master.service.consul' {
        include docker
        class {'docker':}
}```

Thanks

**Comment by davejrt** [comment]
Hi @hamon-e we only support >= puppet 4.0 as per the metadata.json 

https://github.com/puppetlabs/puppetlabs-docker/blob/bc714f289327524a4feefd073e474288f5d3c362/metadata.json#L47

**Comment by scotty-c** [comment]
closing due to the requirements in the metadata.json
