### ISSUE TITLE
[Feature] - restart container if reported as unhealthy

### ISSUE THREAD

**Issue by mlukowicz** [puppetlabs/puppetlabs-docker#216]
Hello!

Currently docker does not implement restart upon reporting unhealthy (via HEALTHCHECK directive).
It would be nice if we can define container to be restarted if it is misbehaving - meaning running but not doing what we want.

Michał

**Comment by scotty-c** [comment]
@mlukowicz How are you running the container with Puppet?
Would you be able to attach an example

**Comment by mlukowicz** [comment]
I am currently not using swarm.

I simply use docker::run with manage option.

docker::run { 'myapp':
    image               => 'myregistry/myapp',
    ports               => ['5555:5555','6666:6666'],
    expose              => ['5555','6666'],
    restart_service     => true,
    pull_on_start       => true,
  }

**Comment by mlukowicz** [comment]
PS: currently i am doing that by simply defining cron job that extract this info from docker ps output and restart container if necessary - but it would be nice to have that in module.
