### ISSUE TITLE
Compose install doesn't appear to use proxy setting

### ISSUE THREAD

**Issue by vidkun** [puppetlabs/puppetlabs-docker#229]
When defining a `proxy` in class `docker`, it is not populated in the curl command from the `docker::compose` class.

Setting the `proxy` parameter results in the following curl command error:
`'curl -s -S -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose-1.9.0' returned 6 instead of one of [0]`

The proxy should be right after the `-L` according to `compose.pp`.

**Comment by scotty-c** [comment]
@vidkun The proxy in the `docker` class is a different variable from the `docker::compose` class. You will need to set that proxy with `$docker::compose::proxy`

**Comment by davejrt** [comment]
Closing as a working solution has been provided
