### ISSUE TITLE
test for and enable redhat workstation repository

### ISSUE THREAD

**Issue by sknolin** [puppetlabs/puppetlabs-docker#234]
## What you expected to happen?
When running on redhat enterprise workstation, use workstation repository, don't assume everything is a server based on $::operatingsystem == 'RedHat'

## What happened?

Error: Execution of '/bin/yum -d 0 -e 0 -y --enablerepo=rhel-7-server-extras-rpms install docker-ce' returned 1: Error getting repository data for rhel-7-server-extras-rpms, repository not found

## How to reproduce it?

Run the class on redhat enterprise workstation.

## Versions:

```
$ puppet --version
4.10.8
$ docker version
18.03.1-ce

$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "Maipo",
    description => "Red Hat Enterprise Linux Workstation release 7.5 (Maipo)",
    id => "RedHatEnterpriseWorkstation",
    release => {
      full => "7.5",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
```

## Logs:
```
Paste any relevant logs from a puppet run
```

**Comment by sknolin** [comment]
In params.pp I just did this:

```
     if $::operatingsystem == 'RedHat' {
        if $::os['distro']['id'] == 'RedhatEnterpriseWorkstation' {
          $repo_opt = '--enablerepo=rhel-7-workstation-extras-rpms'
        } else {
          $repo_opt = '--enablerepo=rhel-7-server-extras-rpms'
```

I know there's a recent ticket that was closed saying to override repo_opt [https://github.com/puppetlabs/puppetlabs-docker/issues/193](193) - but if looking up that it's redhat anyway, why not go all the way to the correct repo so it's correct by default?

**Comment by davejrt** [comment]
hi @sknolin RedHat Enterprise Workstation is not an officially supported operating system in this module. If it works with the work arounds you've put in for your use case, then we're happy for you to fork the module but we won't be implementing any changes related to support of non server OS

**Comment by sknolin** [comment]
That’s fine, but it seems like docker’s a pretty common thing on workstations, and redhat server and workstation.. pretty much the same thing. I don’t get the resistance to test for yet another string.

Scott

**Comment by scotty-c** [comment]
@sknolin The issue is if we had support for RedHat desktops we will need to support all linux desktops. 
As usually, Docker is a development tool needs to be changed regularly ie replace the runtime or change the Docker daemon to test. What is the use case with Puppet do this as it centralised management?

**Comment by sknolin** [comment]
@scotty-c At my organization we use puppet to manage servers, workstations, hpc clusters, cluster filessytems - every linux system. Some of those systems need docker, we manage the docker installation via puppet. That doesn't mean we manage all the containers that might be run on every system, but the docker infrastructure.

We use the docker module as one component in the stack (profile). For example, our docker profile might also set kernel flags and sysctl settings for namespace support.

So the use case for puppet is - we use puppet to manage things. Just because it's a workstation, we don't want to go back to banging rocks together and manually installing and configuring software. Isn't this sort of the idea for puppet?

Scott
