### ISSUE TITLE
Support for docker_daemon_environment files

### ISSUE THREAD

**Issue by thatsk** [puppetlabs/puppetlabs-docker#237]
Hello team,

If we want to add some extra configuration in docker daemon. Like if we want to expose Prometheus metrics.

https://docs.docker.com/config/thirdparty/prometheus/

We need to add this parameter. /etc/docker/daemon.json

There is in readme file docker_daemon_environment_files

But not sure how to use in hiera.

Can anyone tell me how to use in hiera.

I want to expose metrics.
{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}

**Comment by mihaibuzgau** [comment]
hi @thatsk, 
the "metrics-addr" and "experimental"  can be added using the "extra_parameters" parameter of the docker class. Below you have an example on how to add this to hiera:

```
docker::extra_parameters:
  - '--metrics-addr=localhost:9323'
  - '--experimental=true'
```

**Comment by thatsk** [comment]
@mihaibuzgau thanks

**Comment by thatsk** [comment]
you need to add in readme also this is very useful.
