### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by BarnumD** [puppetlabs/puppetlabs-docker#26]
Support installing docker and managing native windows containers on the windows server platform.

**Comment by scotty-c** [comment]
@BarnumD We have this working coming up in a couple of sprints. So watch this  space

**Comment by fgabriel78** [comment]
How is this feature going?

**Comment by davejrt** [comment]
@fgabriel78 we are currently evaluating the windows product in our sandbox environments and hope to start working on this in upcoming sprints.

**Comment by mihaibuzgau** [comment]
@BarnumD we've just pushed Puppet Docker module 2.0.0 that has support for Docker EE on Windows 2016.

**Comment by BarnumD** [comment]
Thanks!  Couple of questions:

1. I don't have a subscription for Docker Enterprise.  Is there support for community edition on Windows?
2. Does this support Hyper-V containers or just Windows server containers?

**Comment by davejrt** [comment]
It's worth noting @BarnumD, docker ee for windows is free. You don't need a subscription key to install the engine. Just pass docker_ee => true to install.

**Comment by glennsarti** [comment]
@mihaibuzgau Is there work in progress to support hyper-v isolation mode?  Particularly given the Server 2016 work to support both Windows and Linux kernels via hyper-v isolation

cc/ @BarnumD
