### ISSUE TITLE
Why is debian-keyring package required on Debian?

### ISSUE THREAD

**Issue by hostingnuggets** [puppetlabs/puppetlabs-docker#281]
I was wondering if on Debian the dependency on the debian-keyring package is really required?

I am mostly asking because I have an annoying dependency cycle as you can see below:

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Anchor[apt_key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 present] => Apt::Key[Add key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 from Apt::Source docker] => Apt::Source[docker] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Package[debian-keyring] => Apt::Source[docker] => Package[apt-transport-https] => Apt::Source[docker])
```

**Comment by hostingnuggets** [comment]
There does not seem to be any dependencies on that particular package as I could simply purge it:

```
$ sudo dpkg -P debian-keyring
(Reading database ... 56302 files and directories currently installed.)
Removing debian-keyring (2017.05.28) ...
```

**Comment by davejrt** [comment]
I'm looking into the history of that line. It was brought over when the repo was forked. Someone in the team will get back to you shortly.

**Comment by hostingnuggets** [comment]
Thanks @davejrt for your first feedback. I am under the impression that this package is not required (or required anymore).

**Comment by davejrt** [comment]
@hostingnuggets I've raised a ticket internally for someone to pick this up before the next release. My gut feeling is the same as yours but we'll just need to ensure we're not going to introduce any breaking changes to other users.

**Comment by hostingnuggets** [comment]
@davejrt Perfect, cheers :+1:

**Comment by hostingnuggets** [comment]
It is happening all the time, as soon as I include this module. I am using v4.5.1 of puppetlabs-apt module and I am already aware of the workaround and using it, else I wouldn't be able to use the docker module at all.

**Comment by davejrt** [comment]
Do you have an environment where you can test the latest version of the puppetlabs-apt module to see if it's still an issue?

**Comment by hostingnuggets** [comment]
@davejrt why did this issue get closed so fast? I haven't found time yet to test on a test environment but I will and get back to you.

**Comment by davejrt** [comment]
We have tested internally and removed the dependency in master. Apologies if the PR didn’t reference the issue correctly and caused some confusion

**Comment by hostingnuggets** [comment]
@davejrt thank you for your feedback, that's professional! All good from my side if you removed that dependency, I don't need to test either.
