### ISSUE TITLE
deprecated parameter -g for root_dir

### ISSUE THREAD

**Issue by jurim76** [puppetlabs/puppetlabs-docker#287]
## What happened?

In templates/update_docker_image.sh.erb -g parameter is deprecated (docker v18 at least), please use --data-root instead
## Versions:

```
$ puppet --version
4.10.12
$ docker version
18.03.1~ce-0~debian 
$ facter os
Debian 9
$ puppet module list
puppetlabs-docker-2.2.0

## Logs:
```
Paste any relevant logs from a puppet run
```

**Comment by MWilsonPuppet** [comment]
@jurim76 Thanks for raising this. Looks like -g flag was deprecated from version 17.05.0. Ill create a ticket for us to add support for --data-root flag from 17.05.0 and up.

**Comment by MWilsonPuppet** [comment]
functionality added in #306
