### ISSUE TITLE
Windows support uses dangerous hardcoded defaults

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-docker#294]
In commit https://github.com/puppetlabs/puppetlabs-docker/commit/ffe8d3902b600a727af46a799d8a86b42683e657 support was added to make the windows installation idempotent however it uses dangerous hardcoded defaults and is structured in a way that is far more complex that it needs to be.

1. Saving the install file to `'C:/Windows/Temp/install_powershell_provider.ps1'` is dangerous.  That is a hardcoded path the SYSTEM user's temp directory.  Do not assume `C:` is the root drive.  Do not assume `Windows` is the Windows directry.  Instead use the %TMP% (or TEMP) environment variables

2. Saving the file and then executing the powershell is not required.  The PowerShell Exec provider can take the template directly. e.g.
```
        exec { 'install-docker-package':
          command     => template('docker/windows/install_powershell_provider.ps1.erb'),
          provider    => powershell,
          refreshonly => true,
          logoutput   => true,
        }
```
3. The `exec { 'service-restart-on-failure':` uses hardcoded paths for SYSTEM32 and an extraneous `cmd /c` invocation.  You may as well just use PowerShell at this point

4.  The `exec { 'install-docker-package':` shouldn't use the existance of a script file to install Docker.  Even in the PowerShell template it's both checking to see if it's in the correct state, before installing.

Instead the install template should be split out into; a scrpit to determine if the docker installation is in the correct state, and then a script to put the docker installation into the correct state.

This will reduce the execs down to 1 idempotent resource, that doesn't require hardcoded paths.

**Comment by mihaibuzgau** [comment]
Hi @glennsarti,
Thanks for bringing this to our attention.
The items you've described have been fixed in this PR: https://github.com/puppetlabs/puppetlabs-docker/pull/295
