### ISSUE TITLE
Make module play well with puppetlabs-firewall

### ISSUE THREAD

**Issue by hesco** [puppetlabs/puppetlabs-docker#296]
This project seeks to port the weave::firewall:: classes and defined types into the docker module.  

These features enable puppet driven firewall management without breaking a reliable cross-docker-host overlay network under its use. It was motivated by the resistence of the docker/weave iptables rule sets to playing well with a puppet managed firewall. So essentially this module will replicate what those tools do, in the puppet way, so all the components will play well together.

## What you expected to happen?

I expect to be able to manage the firewall rules for public facing docker hosts, without breaking services exposed by my containers.  

## What happened?

It seems I can either let puppet manage all of my firewall rules (including those normally created by docker) or none of them, leaving me to manage them all manually myself.  

## How to reproduce it?

Use the firewall module to manage a firewall rule on a docker host.  It will flush any rules put in place by the docker engine, and make no attempt to recreate those.  

## Anything else we need to know?

I wrote code which does this four years ago.  You can find it here:
https://github.com/hesco/hesco-weave#use-weavefirewall---manage-docker-host-firewall-for-weave 

It is my intention to port that code, which worked and ran in production for us until we stopped using weave, into the docker module which seems to be its natural home.  I will be watching for signs on this feature request that those of you who maintain the upstream repository might be amenable to accepting such a patch.  Please let me know.  

## Versions:

```
$ puppet --version

$ docker version

$ facter os

$ puppet module list
```

## Logs:
```
Paste any relevant logs from a puppet run
```

**Comment by hesco** [comment]
RFC: WIP: Feature/gh296 play well with firewall #307 
https://github.com/puppetlabs/puppetlabs-docker/pull/307

**Comment by lonebrave** [comment]
Is this still a WIP or has it been abandoned? Would love to have this feature.

**Comment by carabasdaniel** [comment]
Hi @lonebrave,
As we have not closed this issue yet, this might be a feature request that we will try to tackle sometime in the future, for now we are mainly focusing on bug fixes.

**Comment by nicodarge** [comment]
Hi,
Do you have any update or roadmap to add this feature ?
