### ISSUE TITLE
On CentOS 7.4, the default docker group is `dockerroot`

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/puppetlabs-docker#30]
It is set to `docker` in params, but it is `dockerroot` on my EL7.4 vagrant image (centos/7).

Setting `docker_group` to 'dockerroot` is a functional workaround, so the default can simply be changed for EL7.

**Comment by davejrt** [comment]
Hi

Can you just clarify exactly what the desired behaviour you're after is? It's not clear from your comments above whether the default group `docker` is being applied or the case statement is being evaluated incorrectly and `dockerroot` is being applied.

**Comment by jeefberkey** [comment]
In the module as it is, `docker` is being set as a smart default for the `docker_group` param. On the newer versions of CentOS (7.4 as tested), the correct group has been changed to `dockerroot`. The following snippet is how I have configured the module on my box using the RedHat vendored docker packages:

```
sysctl {'net.bridge.bridge-nf-call-iptables':  value => 1 }
sysctl {'net.bridge.bridge-nf-call-ip6tables': value => 1 }
class { 'docker':
  use_upstream_package_source => false, 
  service_overrides_template  => false, 
  selinux_enabled => 'true', 
  manage_epel     => false,
  package_name    => 'docker',     
  log_driver      => 'journald',
  docker_group    => 'dockerroot', 
  before          => [
    Sysctl['net.bridge.bridge-nf-call-iptables'],
    Sysctl['net.bridge.bridge-nf-call-ip6tables']
  ]
}
```
On second thought, you probably shouldn't do this because you can't tell where the package would be installed from. I think `docker` is correct when using `docker-ce`.
