### ISSUE TITLE
[feature] swarm facts

### ISSUE THREAD

**Issue by spali** [puppetlabs/puppetlabs-docker#309]
facts about swarm node status (`docker node ls`).
especially status of the nodes for my use-case where I would need "Manager Status" to execute docker_stack resources only on the leader.
This would allow to not hardcode the stack on a specific node level. 
The big advantage, is, if a node goes down or is drained, automatically the next leader would be responsible for deploying the stack's.

**Comment by jrevillard** [comment]
I'm very interested into this also :-) !
