### ISSUE TITLE
docker_group set in init.pp is not referenced in docker::run

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/puppetlabs-docker#321]
https://github.com/puppetlabs/puppetlabs-docker/blob/9fc47a10f180b4b8597983ada39f000f2ff76feb/manifests/run.pp#L138

I have set `docker::docker_group` a `docker` class declaration, but I am unable to use the `docker::run` define because it always checks the params class, which contains the incorrect default. My system uses dockerroot as the docker_group

**Comment by davejrt** [comment]
Can you post an example of you're actually defining the class and where it isn't working?

If you're including this module this is how I'd expect it do be done, and I'd expect this to work. 

```puppet
class { 'docker':
  docker_group => 'dockerroot',
}
```

**Comment by jeefberkey** [comment]
I have a profile module with acceptance tests here: https://github.com/simp/pupmod-simp-simp_docker/

In the [default suite](https://github.com/simp/pupmod-simp-simp_docker/tree/master/spec/acceptance/suites/default), I just include my profile and use a bunch of the defines in this module.

The profile module works by building up a hash of default params depending on a few facts, then using a splat operator. https://github.com/simp/pupmod-simp-simp_docker/blob/master/manifests/init.pp#L81-L83

**Comment by davejrt** [comment]
Happy to take a PR with passing tests to fix this. We've had one previously that was submitted without tests passing so we weren't able to merge it at that point. 

PR #250

**Comment by esalberg** [comment]
I'm working on the spec tests for #250 currently - the strict variables are being difficult, but I"m making progress.

**Comment by jeefberkey** [comment]
@esalberg thanks for pointing me there, I didn't look at PRs. I will follow that issue

**Comment by davejrt** [comment]
I'm going to close this due to a lack of inactivity here and on the PR in question. The PR looked fine aside from the feedback that was originally left. Please feel free to reopen the PR addressing the feedback discussed and we'll be happy to look at getting it merged.
