### ISSUE TITLE
Redeploy stack exec

### ISSUE THREAD

**Issue by longnameislong** [puppetlabs/puppetlabs-docker#322]
## What you expected to happen?
I require that my stacks are redeployed each run when a change is detected. I am using a file resource to deploy my stack file and when that deploys a change I and using a subscribe on my stack class to run the new exec I have added below.

## How to reproduce it?
Deploy a stack and then change the stack file, run puppet with changes and the changes will not be added as the unless option exists

## Anything else we need to know?
FYI - I am very new to GIT and puppet that is why I am raising this as an issue instead of a pull, apologies

Could I please ask for this to be added to the module as I am currently running a fork of the project that includes this change. 

## Code: -extract of stacks.pp
```
if $ensure == 'present'{
      $docker_stack_flags = docker_stack_flags ({
      stack_name => $stack_name,
      bundle_file => $bundle_file,
      compose_file => $compose_file,
      prune => $prune,
      with_registry_auth => $with_registry_auth,
      resolve_image => $resolve_image,
      })

      $exec_stack = "${docker_command} deploy ${docker_stack_flags} ${stack_name}"
      $unless_stack = "${docker_command} ls | grep ${stack_name}"

      # If you need to redeploy a stack, you can notify Docker::Stack[$stack_name]
      exec { "docker stack refresh ${stack_name}":
        refreshonly => true,
        command     => $exec_stack,
        path        => ['/bin', '/usr/bin'],
        before      => Exec["docker stack create ${stack_name}"],
      }

      exec { "docker stack create ${stack_name}":
        command => $exec_stack,
        unless  => $unless_stack,
        path    => ['/bin', '/usr/bin'],
    }
  }
```

**Comment by davejrt** [comment]
I've created a ticket and added this to our internal backlog

**Comment by PierreR** [comment]
I have the same problem. When my docker-compose file changes, there is a notify to trigger a redeploy but nothing happens (even if the logs seems to say otherwise with : 
```

**Comment by mattstrain** [comment]
So we were having the same issue as this but if I update to the new version and use this new type I get a notice message on every puppet run?
``
Notice: /Stage[main]/xxx_docker::Service::Stack[v52]/Docker_stack[v52]/ensure: created
``

**Comment by davejrt** [comment]
@mattstrain can you please provide a manifest and a more complete log file?

**Comment by kwek** [comment]
Are you sure this is fixed? Triggering a refresh on docker::stack does not refresh it. The same applies for docker_stack. 

I applied the changes in https://github.com/puppetlabs/puppetlabs-docker/pull/657 . But not sure how this fix this for docker_stack. Any hints?
