### ISSUE TITLE
Remove containers

### ISSUE THREAD

**Issue by markvr** [puppetlabs/puppetlabs-docker#33]
Once a container is started with `docker::run` is there anyway to stop and remove it?  I can't see anything in the docs, I imagine something like:

    docker::run{'service':
      ensure => absent
    }

Which should stop and remove all the associated systemd services etc as well.

Even better would be a `purge` option on the main class that automatically removed any containers that weren't specified in a `docker::run` statement.

**Comment by davejrt** [comment]
Hi Markvr

You're correct in saying this functionality doesn't exist. We will create a ticket and look at adding this functionality in an upcoming release.

**Comment by davejrt** [comment]
This was added in PR #61
