### ISSUE TITLE
Missing subnets in docker::network

### ISSUE THREAD

**Issue by CAPSLOCK2000** [puppetlabs/puppetlabs-docker#351]
## What you expected to happen?
When defining a network with docker::network I expect all subnets to be added, not just the first one.
This works fine for gateways and ip-ranges, but not for the subnets.

## What happened?
I use the following code to define a network that contains various IP-ranges.
Most importantly, it contains both an IPv4-range and an IPv6-range, as is required on multi-stack networks.
However additional subnets are ignored:

```
 docker_network { 'testnet':
    ensure   => present,
    driver   => 'macvlan',
    subnet   => [ '192.168.3.0/24', '2001:984:3be3:3::0/64', '10.0.0.0/24'],
    gateway  => [ '192.168.3.1', '2001:984:3be3:3::1', '10.0.0.1'],
    options  => 'parent=br19',
  }

Error: /Stage[main]/Mydocker::Host/Docker_network[testnet]/ensure: change from 'absent' to 'present' failed: 
Execution of '/usr/bin/docker network create --driver=macvlan --subnet=192.168.3.0/24 --gateway=192.168.3.1 --gateway=2001:984:3be3:3::1 --gateway=10.0.0.1 --opt=parent=br19 testnet' returned 1: every ip-range or gateway must have a corresponding subnet
```

Obviously the --subnet option is provided only once, instead of for every subnet.

## Versions:

root@raki:~# puppet --version
5.5.6

$ docker version
root@raki:~# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:06 2018
  OS/Arch:          linux/amd64
  Experimental:     false

root@raki:~# facter os
{
  architecture => "amd64",
  distro => {
    codename => "sid",
    description => "Debian GNU/Linux unstable (sid)",
    id => "Debian",
    release => {
      full => "unstable",
      major => "unstable"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "buster/sid",
    major => "buster/sid"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
root@puppet:~# puppet module list
/etc/puppet/code/environments/production/modules
├── aptkey (???)
├── dummy (???)
├── nagios (???)
├── puppetlabs-docker (v3.0.0)
├── puppetlabs-image_build (v0.7.0)
├── puppetlabs-powershell (v2.1.5)
├── puppetlabs-reboot (v2.0.0)
├── puppetlabs-translate (v1.1.0)
├── ssmtp (???)
└── stahnma-epel (v1.3.0)
/usr/share/puppet/modules
├── puppetlabs-apt (v4.5.1)
└── puppetlabs-stdlib (v4.25.1)

## Logs:
```
Error: /Stage[main]/Mydocker::Host/Docker_network[testnet]/ensure: change from 'absent' to 'present' failed: 
Execution of '/usr/bin/docker network create --driver=macvlan --subnet=192.168.3.0/24 --gateway=192.168.3.1 --gateway=2001:984:3be3:3::1 --gateway=10.0.0.1 --opt=parent=br19 testnet' returned 1: every ip-range or gateway must have a corresponding subnet
```

**Comment by davejrt** [comment]
Hi

Thanks for the info and raising this issue. We'll get someone to look into it. Are you able to tell me, how you're running the services on top of the network once it's been defined. For example, have you considered creating the network inside a compose/stack file as a workaround while we get this feature added?

**Comment by CAPSLOCK2000** [comment]
On 08-10-18 07:02, davejrt wrote:
> Hi
> 
> Thanks for the info and raising this issue. We'll get someone to look
> into it. Are you able to tell me, how you're running the services on top
> of the network once it's been defined. For example, have you considered
> creating the network inside a compose/stack file as a workaround while
> we get this feature added?
> 

Hi,
thanks for looking into this.

I worked around it by using additional_flags of docker_network to
specify all options by hand, for example:


 docker_network { 'dmz':
    ensure   => present,
    driver   => 'macvlan',
    options  => 'parent=br1',
    additional_flags => [ "--subnet=192.168.1.0/24",
                          "--gateway=192.168.1.1",
                          "--ip-range=192.168.1.208/28",
                          "--subnet=2001:0db8:0:1::0/64",
                          "--gateway=2001:0db8:0:1::1",
                          "--ip-range=2001:0db8:0:1:0100::0/72",
                        ],
  }

-- 
Casper Gielen
