### ISSUE TITLE
Unable to set unit dependencies other then .service

### ISSUE THREAD

**Issue by sirhopcount** [puppetlabs/puppetlabs-docker#352]
Hi,

When setting a (systemd unit) dependency via `depend_services` the `.service` extension is  added via the erb template but there are different types of units (e.g. .sock, .mount, .device, etc).

So it's currently impossible to create a dependency on anything else than a service.

In my case I need to ensure that an EFS volume is mounted before the docker container is started but adding the unit to `depend_services` results in the follow configuration:

```
[Unit]
Description=Daemon for jenkins
After=docker.service srv.mount.service
Wants=
Requires=docker.service srv.mount.service
```

Which results in a failure during reload:

```
Failed to start docker-jenkins.service: Unit srv.mount.service not found.
```

Reference:

https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files

**Comment by davejrt** [comment]
Are you able to fill out the template? I can't see how this is an issue with the docker module without a bit more information.

**Comment by sirhopcount** [comment]
sure no problem.

## What you expected to happen?
I want  to create a dependency on a EFS mount so the container does not start before the mount is present.  To achieve this I add `depend_services` with and dependency on `srv.mount`

```puppet
  ### Run jenkins instance
  docker::run { 'jenkins':
    image           => 'jenkins/jenkins:lts',
    hostname        => 'jenkins',
    username        => '10051',
    ports           => ['127.0.0.1:8080:8080','50000:50000'],
    volumes         => '/srv/jenkins:/var/jenkins_home',
    depend_services => ['srv.mount'],
    require         => File['/srv/jenkins'],
  }
```

## What happened?

When the unit file is generate the dependencies are defined as following.

```
[Unit]
Description=Daemon for jenkins
After=docker.service srv.mount.service
Wants=
Requires=docker.service srv.mount.service
...
```

Because `.service` has been appended to `srv.mount` the jenkins service fails to start due to the following error:

`Failed to start docker-jenkins.service: Unit srv.mount.service not found.`

## How to reproduce it?

Set a dependency on a systemd unit that is not a service.

## Anything else we need to know?

The problem is that the erb template for  `docker::run` (`templates/etc/systemd/system/docker-run.erb`) has this snippet:

```erb
<%-
	@after = [@service_name+".service"] +
		@sanitised_after_array.map{ |s| "#{@service_prefix}#{s}.service"} +
		@sanitised_depends_array.map{ |s| "#{@service_prefix}#{s}.service"} +
		@depend_services_array.map{|s| "#{s}.service"}
	@wants = @sanitised_after_array.map{ |a| "#{@service_prefix}#{a}.service"}
	@requires = [@service_name+".service"] +
		@sanitised_depends_array.map{ |d| "#{@service_prefix}#{d}.service"} +
		@depend_services_array.map{|s| "#{s}.service"}
-%>
```

Which append `.service` to all defined dependencies. I know the name `depend_services` implies that only services can be defined but in the case of systemd this limits its use as systemd has many other units that can be defined as dependencies ( `.socket`, `.device`, `.mount`, etc).

So its not as much a bug/issue with the docker module itself it just an assumption being made about the type of dependencies that can be defined in a systemd unit.

## Versions:

```bash
$ puppet --version
4.10.12
```

```bash
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

```bash
$ facter os
{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.5 (stretch)",
    id => "Debian",
    release => {
      full => "9.5",
      major => "9",
      minor => "5"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.5",
    major => "9",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
```

```Puppetfile
forge "https://forgeapi.puppetlabs.com"
...
mod 'puppetlabs-docker', '3.0.0'
...
```

**Comment by davejrt** [comment]
Thanks for the extra info. We'll get a ticket created internally and address this in an upcoming release.
