### ISSUE TITLE
How do I uninstall the legacy `docker` package(s) first?

### ISSUE THREAD

**Issue by AnthonyMastrean** [puppetlabs/puppetlabs-docker#363]
It's common that older servers or mistaken users have installed the legacy `docker` package, sometimes from the distribution package repository (the package is still available to install). This module does not automatically manage the old package or its [_long_ list of dependencies](https://docs.docker.com/install/linux/docker-ce/centos/#uninstall-old-versions).

I can't use the resource-title/name because your module declares the same resource title.

```puppet
package { 'docker':
    ensure => absent,
}
```

I have to use an alias. That's OK (although, it doesn't play nice with resource title arrays).

```puppet
package { 'legacy-docker':
    ensure => absent,
    name => 'docker',
}
```

I can't use a normal `package` resource to remove the deps, because I get into an ordering problem on subsequent puppet `apply`s (the `package` resource has no `refreshonly` like syntax).

```puppet
package { 'legacy-docker':
    ensure => absent,
    name => 'docker',
}

package { [
    'docker-client',
    'docker-client-latest',
    'docker-common',
    'docker-latest',
    'docker-latest-logrotate',
    'docker-logrotate',
    'docker-selinux',
    'docker-engine-selinux',
    'docker-engine',
]:
    ensure => absent,
}
```

```
Error: Execution of '/bin/rpm -e container-selinux-2.68-1.el7.noarch' returned 1: error: Failed dependencies:
        container-selinux >= 2.9 is needed by (installed) docker-ce-18.06.1.ce-3.el7.x86_64
Error: /Stage[main]/Profile::Docker/Package[docker-selinux]/ensure: change from 2.68-1.el7 to absent failed: Execution of '/bin/rpm -e container-selinux-2.68-1.el7.noarch' returned 1: error: Failed dependencies:
        container-selinux >= 2.9 is needed by (installed) docker-ce-18.06.1.ce-3.el7.x86_64
Error: Execution of '/bin/rpm -e container-selinux-2.68-1.el7.noarch' returned 1: error: Failed dependencies:
        container-selinux >= 2.9 is needed by (installed) docker-ce-18.06.1.ce-3.el7.x86_64
Error: /Stage[main]/Profile::Docker/Package[docker-engine-selinux]/ensure: change from 2.68-1.el7 to absent failed: Execution of '/bin/rpm -e container-selinux-2.68-1.el7.noarch' returned 1: error: Failed dependencies:
        container-selinux >= 2.9 is needed by (installed) docker-ce-18.06.1.ce-3.el7.x86_64
```

So, I'm stuck writing a platform dependent `exec` resource.

```puppet
package { 'legacy-docker':
    ensure => absent,
    name => 'docker',
    notify => Exec['autoremove'],
}

exec { 'autoremove':
    command => '/usr/bin/yum -y autoremove',
    refreshonly => true,
}
```

Then I have to make sure that, if these happen, they happen _before_ your module. But, you can't resource chain an `include` statement, so now I need to use the `class` form (even if I didn't want to).

```puppet
package { 'legacy-docker':
    ensure => absent,
    name => 'docker',
    notify => Exec['autoremove'],
}

exec { 'autoremove':
    command => '/usr/bin/yum -y autoremove',
    refreshonly => true,
}

class { 'docker':
    require => [
        Exec['autoremove'],
        Package['legacy-docker'],
    ]
}
```

Is this all really necessary? Is there some other method I'm missing? If this is actually "it", would you consider taking on this requirement? It's _specifically_ documented in the _official_ installation instructions, so I'd say it's a core activity!

**Comment by davejrt** [comment]
Did you install the package with Puppet to begin with? Managing packages and resources not previously configured with this module is beyond the scope, especially if you are using distro packages or some sort of custom configuration. At some point we have to draw a line in the sand on what we do and don't support here.

**Comment by AnthonyMastrean** [comment]
Yeah, I previously used a basic `package` resource.

```puppet
package { 'docker':
    ensure => latest,
}
```

But, the distribution package ends up out-of-date. I want to migrate to the supported Docker package repository and latest package. I thought I would do that via the supported module, which appears to implement the official instructions (which include instructions to remove legacy packages).

Manifests are not migrations, so I can't write a "temporary" manifest revision that removes the legacy package _before_ using the supported module. I can't guarantee this will run on all my boxes. Or that I'll never have another old box come online.

```puppet
package { 'docker': 
    ensure => absent,
}
```

I _need_ to be able to specify that legacy packages are absent and new packages are present _at the same time!_

**Comment by davejrt** [comment]
I've looked at the issue you've raised against the docker-ce repo and seen the feedback they've given. 

As previously stated, I think the solution in your specific case is to construct another class to tidy up what was previously installed by another module or class.
