### ISSUE TITLE
TCP bind example doesn't work

### ISSUE THREAD

**Issue by joelgarboden** [puppetlabs/puppetlabs-docker#372]
TCP bind example doesn't work

`Error starting daemon: Error initializing network controller: Error creating default "bridge" network: auxilairy address: (DefaultGatewayIPv4:10.20.0.1) must belong to the master pool: 172.17.0.0/16`

```
class { 'docker':
  tcp_bind        => ['tcp://127.0.0.1:4243'],
  socket_bind     => 'unix:///var/run/docker.sock',
  ip_forward      => true,
  iptables        => true,
  ip_masq         => true,
  bridge          => br0,
  fixed_cidr      => '10.20.1.0/24',
  default_gateway => '10.20.0.1',
}
```

I removed `tcp://10.0.0.1:4243` from tcp_bind as well.

Likely same issue as upstream documentation. https://github.com/docker/docker.github.io/issues/6891

Ubuntu 18.04 KVM, used `source /etc/default/docker && /usr/bin/dockerd $OPTIONS` to repro and actually output the error.

**Comment by davejrt** [comment]
fixed in PR #374
