### ISSUE TITLE
Fix the documentation (puppet strings + readme)

### ISSUE THREAD

**Issue by vStone** [puppetlabs/puppetlabs-docker#381]
## What you expected to happen?
Find correct documentation in the readme and puppet strings (docs)

## What happened?
Documentation does not match real situation: some parameters in the README.md have already been renamed, parameters in classes have been renamed/removed but the docs have not been adjusted.

## Side note:
Maybe add 'updating the documentation' to the reviewers check-list

**Comment by davejrt** [comment]
I'll have someone audit the documentation before the next release.

**Comment by carabasdaniel** [comment]
Documentation updated in latest release with puppet strings
