### ISSUE TITLE
Add option to remove --enablerepo=extras on CentOS

### ISSUE THREAD

**Issue by 1605200517** [puppetlabs/puppetlabs-docker#388]
On a CentOS host, Puppet produces with this module the following statement:

`yum install --enablerepo=extras docker`

Which does not work (admittedly result of custom configuration of the host environment due to other dependencies).

`yum install docker`

works though.

Maybe it would be good to make the explicit "enablerepo" optional.

**Comment by davejrt** [comment]
What version of the module are you using?

**Comment by davejrt** [comment]
Closing as this is fixed in the later versions of the module.
