### ISSUE TITLE
Swarm mode token

### ISSUE THREAD

**Issue by Vanuan** [puppetlabs/puppetlabs-docker#39]
The documentation of a swarm mode setup seems to be missing something important.
It looks like to manage swarm with puppet I need to provision a token.
But to get the token I need to go to the manager node and type `docker swarm join-token -q`, copy the output and paste it into puppet?

Am I missing something? Or there's some automated way to do that?
What I would expect is this:

```
if(host_has_label("my-swarm-manager")) {
  docker::swarm {'cluster_manager':
    init           => true,
    advertise_addr => current_host_ip(),
    listen_addr    => current_host_ip(),
    swarm_name     => 'my-swarm'
  }
} else if (host_has_label("my-swarm-worker")) {
  docker::swarm {'cluster_worker':
    join           => true,
    advertise_addr => current_host_ip(),
    listen_addr    => current_host_ip(),
    manager_ip     => get_ip_by_swarm_name('my-swarm'),
    token          => get_token_by_swarm_name('my-swarm')
  }
}
```

Is there a tutorial on how to do something like this?

**Comment by davejrt** [comment]
Hi

We'll be handling this in an upcoming release, but for now we don't have a supported method of doing this.

**Comment by mdwheele** [comment]
> We'll be handling this in an upcoming release, but for now we don't have a supported method of doing this.

Does the project keep a public sprint backlog or anything to judge when features like this are coming? I would be super willing to help contribute a feature like this if there weren't already resources applied within your team.

**Comment by davejrt** [comment]
We don't have any public facing sprint backlog, but as of release 1.0.2 we now support puppet tasks to do some of this for you. Unfortunately at this point we still don't have a secure way of dynamically getting this as part of a catalog run. 

But we are more than happy to take PRs on this module and work with the community to meet their needs.

**Comment by scotty-c** [comment]
This is now released in the latest version on the forge https://forge.puppet.com/puppetlabs/docker

**Comment by irux** [comment]
@Vanuan did you solve it ? I would like to do the same!

**Comment by Vanuan** [comment]
@irux  I don't remember, I'm not using puppet anymore.
