### ISSUE TITLE
Amazon Linux support - https://download.docker.com/linux/centos/2017/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by amlodzianowski** [puppetlabs/puppetlabs-docker#392]
Are there any plans on introducing support for Amazon Linux? The following is an output from trying to apply the docker class:

`Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install docker-ce-17.03.2ce-1.59.amzn1' returned 1: One of the configured repositories failed (Docker),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable docker

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=docker.skip_if_unavailable=true

failure: repodata/repomd.xml from docker: [Errno 256] No more mirrors to try.
https://download.docker.com/linux/centos/2017/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

**Comment by davejrt** [comment]
We aren't planning on adding official support, you should be able to override the params to point to the correct repos for AWS though.

**Comment by davejrt** [comment]
You can set the manage repos flag to false, and add the repos using an alternate module and install the package that way. We only provide repo support for the official upstream repos and the OSes listed in the docker documentation.

**Comment by amlodzianowski** [comment]
Thanks for the reply @davejrt , this makes perfect sense with whats on the matrix. The main reason why I was asking is the fact that Amazon Linux used to be supported (back in the 1.0.2 release) and I was wondering if there are any plans to reintroduce this.

We can definitely manage the package outside this module, so I'll be closing out this issue.

**Comment by davejrt** [comment]
Hi

At this stage we dont have plans to do this. I believe we released the
module with the logic for aws and other OS but they were not officially
supported in the metadata.json which is what may have caused the confusion
and that was probably an oversight on our part.

Hopefully this solution in combination with the rest of the module will
serve you well enough
