### ISSUE TITLE
Deploy images from the Amazon AWS ECR registry?

### ISSUE THREAD

**Issue by mpdude** [puppetlabs/puppetlabs-docker#418]
I would like to deploy docker images stored in the AWS ECR "Elastic Container Registry".

The login process is described at https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-basics.html#use-ecr. Basically, you need to execute the command `aws ecr get-login --no-include-email` from their CLI tool. This will print the `docker login` command with a password/token that is valid for 12 hours.

They also have a "credentials helper" available at https://github.com/awslabs/amazon-ecr-credential-helper. This seems to be a wrapper that `docker` will execute when it needs to login, and it will run the above command in turn.

So, my question is: Has anybody managed to use this module with the AWS ECR? What steps are necessary? What tweaks to this module would be needed to make it work?

**Solution:** https://github.com/puppetlabs/puppetlabs-docker/issues/418#issuecomment-684616443

**Comment by davejrt** [comment]
The solution I have seen used in the past, was to write another class that logged in to the registry before hand. 

Then you have the auth token already on the host before you pull the image with the docker module.

**Comment by mpdude** [comment]
That means you basically run the login command every time puppet runs?

**Comment by davejrt** [comment]
I'm not sure if there is a way to check the status of a token with the awscli before hand, but perhaps if there is you could ensure that the login command only runs based on the outcome of a check like that. 

Worst case is yes, it runs every time you run puppet. 

I'll leave this open incase any one else in the community has any better input, but as I mentioned in the past the solutions I have seen used in other places of work has been less elegant, but ultimately got the job done without adverse effects.

**Comment by mpdude** [comment]
20 months later, I faced the same problem again and found this issue through a Google search. I had forgotten I even reported it! 👀 

What seems to work:

* Install https://github.com/awslabs/amazon-ecr-credential-helper: Follow their README to compile the `docker-credential-ecr-login` binary (a portable Go binary) and place it on your `PATH`. (I use a simple Puppet `file` to distribute the binary.)
* Use Puppet to set up `~root/.docker/config.json` to read `{ "credsStore": "ecr-login" }`. You can also limit this to your ECR URL, see [here](https://github.com/awslabs/amazon-ecr-credential-helper#docker).
* The credentials helper will automagically run the `aws ecr get-login` command when Docker needs to access the registry.

Now you only need to make sure the underlying `aws ecr ...` command has the necessary IAM permissions, credentials etc ([documentation](https://github.com/awslabs/amazon-ecr-credential-helper#aws-credentials)). One way to solve that is to use EC2 instance profiles, and assign the one of the [AWS managed ECR policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html) to the IAM role you're using for this.

For additional reference, here's an AWS blog post on the credential helper:
https://aws.amazon.com/de/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

When you use `exec { 'docker ...' ... }` from Puppet, make sure the `PATH` contains not only `docker`, but also the credentials helper. This might not be the case if the latter is located e. g. in `/usr/local/bin/`.
