### ISSUE TITLE
Pinned version of puppetlabs/reboot is too strict.

### ISSUE THREAD

**Issue by madelaney** [puppetlabs/puppetlabs-docker#419]
## What you expected to happen?
I'd expect the required version range of `puppetlabs/reboot` to be more forgiving given that the usage is very limiting.

## What happened?
While trying to resolve dependencies in modules, the requirement of `puppetlabs/reboot`, causes an issue.

## How to reproduce it?
Allow for a range vs. hard code version `2.0.0`

## Versions:
```
$ puppet --version
4.10.12

$ docker version
18.09.0, build 4d60db4

$ facter os
{"name"=>"Darwin", "family"=>"Darwin", "release"=>{"major"=>"18", "minor"=>"2", "full"=>"18.2.0"}}

$ puppet module list
```

## Logs:
```
[Librarian] Conflict between puppetlabs-reboot (= 2.0.0) <https://forge.domain.com> and puppetlabs-reboot/2.1.2 <https://forge.domain.com>
```

**Comment by davejrt** [comment]
We'll do some testing testing and if we don't find any issues, update and push out a small release with the fix.
