### ISSUE TITLE
Unable to Apply Engine Labels

### ISSUE THREAD

**Issue by RXM307** [puppetlabs/puppetlabs-docker#43]
/modules/docker/templates/etc/sysconfig/docker.systemd.erb
  Line: 25
  Detail: undefined method `each' for "[owner=blah, myservice=1, role=myrole]":String
 at /etc/puppetlabs/code/environments/test/modules/docker/manifests/service.pp:193:18 

Similar to $dns should be able to set the docker.systemd.erb template as
<% if @labels %><% @labels_array.each do |label| %> --label <%= label %><% end %><% end -%>

and add the below to service.pp
$labels_array = any2array($labels)

Unless I've missed something?

**Comment by RXM307** [comment]
Fixed and tested in my Fork https://github.com/RXM307/puppetlabs-docker, Please Merge.
Still need to investigate why settings are being applied to /etc/sysconfig/docker instead of /etc/sysconfig/docker-latest though

**Comment by scotty-c** [comment]
@RXM307 can you please raise a PR for the changes.

Thanks in advance

**Comment by RXM307** [comment]
Pull Request #48 Raised, will raise another issue for the sysconfig issues with some patches
