### ISSUE TITLE
Add CE Edition Install Support for Windows

### ISSUE THREAD

**Issue by tek0011** [puppetlabs/puppetlabs-docker#438]
** Is this a FEATURE REQUEST? **
Yes.

## What you expected to happen?
`include docker` should install docker on Windows.  CE Edition or latest Docker Enterprise.  

## What happened?
 
> Resource Statement, Evaluation Error: Error while evaluating a Function Call, This module only work for Docker Enterprise Edition on Windows.

## Anything else we need to know?
Documentation makes it seem like this module works on Windows, installation should be supported.  Support via chocolatey?

**Comment by davejrt** [comment]
Hi @tek0011 

With regards to CE on Windows, that is not on the roadmap for this module. The intention of this module is to track the upstream repos, which is to support production ready version of the engine, not development tools such as Docker Desktop for Mac or Windows.

With regards to your second point, will will discuss internally the logic around `include docker` and the usability of the module, and ensure that the documentation more accurately reflects this.

**Comment by carabasdaniel** [comment]
Closing this issue according to the latest changes on Docker.
Addressing Docker windows install requires an overhaul on the installation approach and we would consider that a bug fix at this point that will need to be addressed for future support.
