### ISSUE TITLE
Need to manage docker.socket on RHEL (also socket overrides)

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-docker#439]
## What happened?
As of Docker-ce 18.09.1, the systemd docker.socket is required on RHEL.  This file has a default SocketGroup of docker (even though the docker group is optional per the Docker documentation).  We need a way to override the SocketGroup setting (in /usr/lib/systemd/system/docker.socket).

## How to reproduce it?
On RHEL with Docker 18.09.1+, run "groupdel docker" and try to restart Docker.  it will fail due to the group on /var/run/docker.sock no longer existing (turns numeric).  The initial install / upgrade is fine because the docker group is added by default.

## Anything else we need to know?
I am submitting a PR for this issue tomorrow, which will have more details as to the fix.  I did have a couple of questions I thought I'd ask here, in case this gets seen before the PR:

1) The current docker-systemd-reload-before-service does not actually notify the service to restart.  Is that on purpose, or may I change the before => to a notify => ?

      exec { 'docker-systemd-reload-before-service':
        path        => ['/bin/', '/sbin/', '/usr/bin/', '/usr/sbin/'],
        command     => 'systemctl daemon-reload > /dev/null',
        before      => $_manage_service,
        refreshonly => true,
      }

This is the only breaking change that I'm planning - otherwise, the new socket override settings will default to false overall.

2) The new socket-overrides-rhel.conf.erb file simply has the following:
[Socket]
SocketGroup=<%= @socket_group %>

Any idea if the same would work for Debian?  If so, I can change the overrides file to socket-overrides.conf.erb and specify it as the default file for both.  I don't have Debian so can't check.

**Comment by davejrt** [comment]
closed by #441
