### ISSUE TITLE
Dependency version ranges too strict

### ISSUE THREAD

**Issue by olavmrk** [puppetlabs/puppetlabs-docker#444]
The version requirements for the dependencies of this module are somewhat strict, which makes it hard to upgrade this module beyond version 3.1.0 (where it was missing upper limits of versions).

This module has the following dependencies:

* [puppetlabs/stdlib](https://forge.puppet.com/puppetlabs/stdlib): >= 4.24.0 <= 5.1.0
* [puppetlabs/apt](https://forge.puppet.com/puppetlabs/apt): >= 4.4.1 <= 6.2.1
* [puppetlabs/translate](https://forge.puppet.com/puppetlabs/translate): >= 0.0.1 <=1.2.0
* [puppetlabs/powershell](https://forge.puppet.com/puppetlabs/powershell): >= 2.1.4 <= 2.2.0
* [puppetlabs/reboot](https://forge.puppet.com/puppetlabs/reboot): >=2.0.0 <= 2.1.2

In all cases it depends on specific minor versions, which means that installing this module together with recent versions of other modules is impossible. E.g.:

* [puppetlabs/stdlib](https://forge.puppet.com/puppetlabs/stdlib) 5.2.0
* [puppetlabs/apt](https://forge.puppet.com/puppetlabs/apt) 6.3.0

Most other modules have more relaxed version requirements, and instead trusts the other modules to use semantic versioning to avoid breaking things. Could this module be updated to use the same system? E.g.:

* [puppetlabs/stdlib](https://forge.puppet.com/puppetlabs/stdlib): >= 4.24.0 < 6.0.0
* [puppetlabs/apt](https://forge.puppet.com/puppetlabs/apt): >= 4.4.1 < 7.0.0
* [puppetlabs/translate](https://forge.puppet.com/puppetlabs/translate): >= 0.0.1 < 2.0.0
* [puppetlabs/powershell](https://forge.puppet.com/puppetlabs/powershell): >= 2.1.4 < 3.0.0
* [puppetlabs/reboot](https://forge.puppet.com/puppetlabs/reboot): >=2.0.0 < 3.0.0

It would ensure that this module does not block updates of other modules, and that other modules don't block updates of this module. At the moment I am stuck at installing version 3.1.0 of this module.

**Comment by davejrt** [comment]
Thanks for the feedback. We will address this shortly and get a release out this week.

**Comment by davejrt** [comment]
fixed in #453

**Comment by lnemsick-simp** [comment]
When will this be released?

**Comment by AMoghrabi** [comment]
Also looking for the release, having issues installing it.

**Comment by davejrt** [comment]
3.3.0 has been released

**Comment by lnemsick-simp** [comment]
Thank you for releasing 3.5.0 so quickly
