### ISSUE TITLE
More Puppet-like deployment of Docker Services

### ISSUE THREAD

**Issue by jacksgt** [puppetlabs/puppetlabs-docker#449]
Hello,

after having used the Docker Services interface of this module, I feel like it's not really designed the way Puppet is supposed to be used.

Take this example from the Readme:
```
To create a Docker service, add the following code to the manifest file:

docker::services {'redis':
    create => true,
    service_name => 'redis',
    image => 'redis:latest',
  }
```

But then when you want to change any of the service parameters (like image, replicas, mount points, published ports...), you have to create an additional Puppet resource:

```
To update the service, add the following code to the manifest file:

docker::services {'redis_update':
  create => false,
  update => true,
  service_name => 'redis',
  replicas => '3',
}
```

Now while Docker happily applies these update-resources multiple times (e.g. ` docker service update --env-add 'HELLO=WORLD' redis`), this means that you have to (over time) add more and more update resources (to delete/add parameters) to your Puppet code (if you want to keep the service running).

But when you remove one of the update resources the Docker service stays in the same state (because Docker does not know the resource was dropped)!
At this point Puppet no longer manages the state of the machine, but merely executes whimsical commands on top of it.

----

In my opinion, the way this should work is by specifying the entire service within *one* Puppet resource and then module figures out what to do.

1.  Check the current service state with `docker service inspect`
2. Create the service if it does not exist
3. Update the service with the appropriate parameters (via `docker service update --XYZ-add` and `--XYZ-rm`)

Since [docker service inspect](https://docs.docker.com/engine/reference/commandline/service_inspect/) provides all the necessary information about a service, figuring out how to change a service should be doable by diffing the output against the desired state specified in Puppet code.

What do you think?

**Comment by davejrt** [comment]
I think this would probably be better done in a type/provider. How do see the puppet code being compared to the output of docker inspect? Genuine question, as I am puzzling trying to work out the best way we'd do it.

**Comment by jacksgt** [comment]
I was not trying to say this functionality has to be implemented in Puppet code (sorry for being a bit unclear there), but rather that the module itself should have such a 'type'.

Did you get my general idea (minus the implementation details) or is it still unclear?

**Comment by davejrt** [comment]
Yep, I agree with the idea...I was just interested to know if you had any initial thoughts about implementation, and more so opening the door for a discussion with the community to see if there are some ideas out there on how to achieve this cleanly.

**Comment by jacksgt** [comment]
It's good to hear that there is an interest from Puppetlabs in implementing this.

I think the `docker_stack` type is a good first start and provides a nice interface between Puppet and Docker Swarm. A similar thing for individual Swarm services would be great.

**Comment by khaefeli** [comment]
I'd also vote to integrate it as type/provider.

**Comment by iainhallam** [comment]
This would still be a helpful way of addressing Docker services.

**Comment by iainhallam** [comment]
The documentation for this module still says it needs an update resource. How is the issue completed?
