### ISSUE TITLE
Incorrect StarLimit systemd unit options

### ISSUE THREAD

**Issue by elexpander** [puppetlabs/puppetlabs-docker#456]
The option `StartLimitInterval` does not exist, it should be named `StartLimitIntervalSec`.

Also these 2 options should be under the `Unit` section and not the `Service` section.

Current options:
```
[Service]
StartLimitInterval=20
StartLimitBurst=5
```

Expected options:
```
[Unit]
StartLimitIntervalSec=20
StartLimitBurst=5
```

Systemd doc: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval

Code ref: 
https://github.com/puppetlabs/puppetlabs-docker/blob/84e8edc3f660fe97b170ee6d6c2e3a9b7a422be4/templates/etc/systemd/system/docker-run.erb#L15-L25

**Comment by davejrt** [comment]
Thanks for the information. As always we're open to community PR's, otherwise myself or someone will get this fixed in the next few days.

**Comment by shamil** [comment]
On Ubuntu 16.04, we are getting errors

```
Unknown lvalue 'StartLimitIntervalSec' in section 'Unit'
```

**Comment by awegmann** [comment]
Getting the same error on CentOS 7.7
