### ISSUE TITLE
Uninstalling Docker on Windows Injects Multiple Environment Variables

### ISSUE THREAD

**Issue by AMoghrabi** [puppetlabs/puppetlabs-docker#457]
## What you expected to happen?

When uninstalling docker-ee on Microsoft Windows 2019, I expect it to remove the docker environment variable only from `Path`.

## What happened?
The module removes the docker environment variable in addition to adding several new environment variables which messes up the Puppet CLI tool.

![Capture](https://user-images.githubusercontent.com/8815903/54306362-6f7e6780-4586-11e9-857a-63d4c1474d5e.PNG)

## How to reproduce it?

1. Install docker using the following manifest:

```
class { 'docker':
  docker_ee => true,
  ensure => 'present'
}
```

2. Uninstall docker using the following manifest:

```
class { 'docker':
  docker_ee => true,
  ensure => 'absent'
}
```

3. Check your environment variables.

## Versions:

```
$ puppet --version
4.9.4

$ docker version
N/A, not installed
$ facter os
{
  architecture => "x64",
  family => "windows",
  hardware => "x86_64",
  name => "windows",
  release => {
    full => "2016",
    major => "2016"
  },
  windows => {
    system32 => "C:\windows\system32"
  }
}

$ puppet module list
C:/ProgramData/PuppetLabs/code/environments/production/modules
├── puppetlabs-apt (v6.2.1)
├── puppetlabs-docker (v3.4.0)
├── puppetlabs-powershell (v2.2.0)
├── puppetlabs-reboot (v2.1.2)
├── puppetlabs-stdlib (v5.1.0)
└── puppetlabs-translate (v1.2.0)
C:/ProgramData/PuppetLabs/code/modules (no modules installed)
```

## Logs:
```
Paste any relevant logs from a puppet run
```

**Comment by AMoghrabi** [comment]
This also happens when upgrading Docker. For example, I specify I want to version lock to `18.09.2`. Puppet installs the correct version and only adds one environment variable for Docker. 

I then specify the version as `18.09.3`. The correct version of Docker is installed but it adds several junk environment variables.

**Comment by AMoghrabi** [comment]
I think I'll have some time tomorrow to look into the code. I'll open a PR if I figure it out! 😄

**Comment by AMoghrabi** [comment]
Hey @davejrt , It turns out this is a bug with the Microsoft Provider Module. I've opened a PR on the module's Github page: https://github.com/OneGet/MicrosoftDockerProvider/pull/58

Thanks for your time.

**Comment by davejrt** [comment]
No worries, we'll leave this open as a guide for anyone coming up with the same issue.

**Comment by AMoghrabi** [comment]
The DockerProvider PR was merged in and it will be released later today to the PSGallery. As far as I can tell we don't need to make any code changes to this module.

I'll close this and reopen if there are further issues after the new DockerProvider is released.

Thanks again.

**Comment by davejrt** [comment]
Thanks for the update
