### ISSUE TITLE
Documentation is misleading about Windows Support.

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-docker#474]
The metadata.json lists Windows as a supported Operating System, however;

* The README says Windows is not supported in the Limitations section ([link](https://github.com/puppetlabs/puppetlabs-docker#limitations))

* The README states the OS limitation of Enterprise Edition only in the Description but not in the OS limitations.

This is confusing and misleading for people trying figure out if this puppet module will work.

**Comment by MassimoSporchia** [comment]
Definitely.
Can you also specify if the docker::run resource works seamlessly between CE and EE?
