### ISSUE TITLE
Exec auth runs with every catalog apply

### ISSUE THREAD

**Issue by catsem** [puppetlabs/puppetlabs-docker#485]
## What you expected to happen?
When private docker registry configured, Exec auth should run once not with every catalog apply.

## What happened?

``
root@moon:~# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for moon.milkyway
Info: Applying configuration version '1558011091'
Notice: /Stage[main]/Docker::Registry_auth/Docker::Registry[foo.bar:5000]/File[/root/registry-auth-puppet_receipt_foo.bar:5000_root]/ensure: defined content as '{md5}3232d3ba033fdfac7de67807b5677e23'
Info: /Stage[main]/Docker::Registry_auth/Docker::Registry[foo.bar:5000]/File[/root/registry-auth-puppet_receipt_foo.bar:5000_root]: Scheduling refresh of Exec[foo.bar:5000 auth]
Notice: /Stage[main]/Docker::Registry_auth/Docker::Registry[foo.bar:5000]/Exec[foo.bar:5000 auth]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 1.47 seconds
``

## How to reproduce it?
Add docker module to your env and config private registry like this (using hiera):

docker::extra_parameters:
    - --userns-remap="default"    
docker::registry_auth::registries:
  'foo.bar:5000':
    username: 'user'
    password: 'password'

## Versions:

```
$ puppet --version
4.10.9

$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

$ facter os
{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.6 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
/etc/puppetlabs/code/environments/production/modules
├── camptocamp-systemd (v2.4.0)
├── example42-network (v3.3.3)
├── puppet-selinux (v1.6.1)
├── puppet-staging (v3.2.0)
├── puppet-zabbix (v6.6.0)
├── puppetlabs-apache (v3.5.0)
├── puppetlabs-apt (v4.5.1)
├── puppetlabs-concat (v4.2.1)
├── puppetlabs-docker (v3.5.0)
├── puppetlabs-firewall (v1.15.3)
├── puppetlabs-inifile (v3.0.0)
├── puppetlabs-mysql (v6.2.0)
├── puppetlabs-nodejs (v999.999.999)
├── puppetlabs-ntp (v8.0.0)
├── puppetlabs-pe_gem (v0.2.0)
├── puppetlabs-postgresql (v5.2.1)
├── puppetlabs-powershell (v2.3.0)
├── puppetlabs-reboot (v2.1.2)
├── puppetlabs-ruby (v1.0.0)
├── puppetlabs-stdlib (v4.25.1)
├── puppetlabs-translate (v1.2.0)
├── saz-ssh (v5.0.0)
├── saz-timezone (v3.4.0)
├── stm-debconf (v2.0.0)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)

## Logs:
```
Paste any relevant logs from a puppet run
```

**Comment by eliaoggian** [comment]
+1

Same here.

**Comment by carabasdaniel** [comment]
Closing the issue as PR was merged
