### ISSUE TITLE
how to define docker_compose declaration in hiera

### ISSUE THREAD

**Issue by thatsk** [puppetlabs/puppetlabs-docker#503]
```YAML
profile::docker

'docker::compose': present
'docker::compose::version': 1.19.0
'docker::ip_forward': false
'docker::iptables': false
'docker::ip_masq': false
'docker::version': 18.09.1-3.el7
'docker::manage_package': false


'docker::compose':
   compose_test:
     image: 'busybox:latest'
     command: '/bin/sh -c "while true; do echo hello world; sleep 1; done"'
```

## What you expected to happen?
it should take compose declaration and run it
## What happened?
nothing was showing

**Comment by thatsk** [comment]
is any syntax is wrong let me know?

**Comment by thatsk** [comment]
Also how to add docker compose file in puppet module itself to use it in hiera

**Comment by thatsk** [comment]
@davejrt

**Comment by westbywest** [comment]
A common pattern in puppet is to create a wrapper class to extend module functionality:
```
class profile::docker (
  Optional[Hash] $compose_files = undef,
  Optional[Hash] $composes = undef,
){

  include docker
  include docker::compose

  if $compose_files {
    $file_defaults = {
      ensure => 'file',
      mode => '0640', # no world-readable
    }
    create_resources('file', $compose_files, $file_defaults)
  }
  if $composes {
    create_resources('docker_compose', $composes)
  }
}
```

**Comment by thatsk** [comment]
@westbywest after declaring this in profile can we declare in hiera as I mentioned

**Comment by thatsk** [comment]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Method call, Class[Profile::Docker]: parameter 'composes' expects a value of type Undef or Hash, got String at /etc/puppetlabs/code/environments/labs/manifests/site.pp:5:45 on node msapi01p1.func-cp.qa.smf1.mobitv

**Comment by thatsk** [comment]
```
cat modules/profile/manifests/docker.pp
class profile::docker(
  Optional[Hash] $compose_files = undef,
  Optional[Hash] $composes = unded,
) {
  include ::docker
  include ::docker::compose
  include ::docker::run_instance
  include ::docker::registry_auth
  if $compose_files {
    $file_defaults = {
      ensure => 'file',
      mode => '0640', # no world-readable
    }
    create_resources('file', $compose_files, $file_defaults)
  }
  if $composes {
    create_resources('docker_compose', $composes)
  }
}
```

**Comment by thatsk** [comment]
```
'docker::composes':
   compose_test:
     image: 'busybox:latest'
     command: '/bin/sh -c "while true; do echo hello world; sleep 1; done"'
```
but got the above error

**Comment by thatsk** [comment]
@westbywest

**Comment by vasugupta32** [comment]
how to add docker-compose file in puppet module itself to use it in hiera

**Comment by vasugupta32** [comment]
> how to add docker-compose file in puppet module itself to use it in hiera

@davejrt

**Comment by chelnak** [comment]
Hey, since this is not an issue with the implementation of the module I am going to close this issue.

I would encourage the discussion to move to our community slack where I am sure it would gain more traction!

https://slack.puppet.com/
