### ISSUE TITLE
docker service detach doesn't work correctly 

### ISSUE THREAD

**Issue by khaefeli** [puppetlabs/puppetlabs-docker#521]
## Describe the Bug
If I set the param `detach` to true, the command executed on the shell doesn't add the `--detach` and waiting for converging. If I set it to false, it's adding the `--detach` option. Which is the opposite of the expected behavior

## Expected Behavior
Add the `--detach` to the cmd and immediately continue the puppet run, while converging the service in the background

## Environment
 - latest puppet 6.8
 - latest puppetlabs/docker module (3.7)
 - Debian 9

Fixed in #520

**Comment by florindragos** [comment]
Merged in https://github.com/puppetlabs/puppetlabs-docker/pull/520
