### ISSUE TITLE
docker_compose restarts container when used in cojunction with notify

### ISSUE THREAD

**Issue by PhilippHomann** [puppetlabs/puppetlabs-docker#524]
## Describe the Bug
Having this simple manifest:
```
$str = "version: '3.3'
services:
  test:
    image: fedora:30
    command: /bin/bash -c 'for i in {0..1000}; do echo \"Running \$\$i\"; sleep 1; done'
"

file{"/tmp/compose/docker-compose.yml":
    ensure => present,
	content => $str,
}

docker_compose { 'test':
	compose_files => ['/tmp/compose/docker-compose.yml'],
	ensure  => present,
	subscribe => File["/tmp/compose/docker-compose.yml"],
}
```
I receive the following output:
```
root@1cd712a1af22:/tmp/compose# puppet apply --verbose /puppet/manifests/init.pp 
Info: Loading facts
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for 1cd712a1af22 in environment production in 0.06 seconds
Info: Applying configuration version '1568101878'
Notice: /Stage[main]/Main/File[/tmp/compose/docker-compose.yml]/ensure: defined content as '{md5}ec4d982e72bfdd96d746b0ce2bbdbc56'
Info: /Stage[main]/Main/File[/tmp/compose/docker-compose.yml]: Scheduling refresh of Docker_compose[test]
Info: Checking for compose project test
Info: Running compose project test
Notice: /Stage[main]/Main/Docker_compose[test]/ensure: created
Info: Checking for compose project test
Info: Checking for compose service test fedora:30
Info: Rebuilding and Restarting all containers for compose project test
Info: Running compose project test
Notice: /Stage[main]/Main/Docker_compose[test]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 3.41 seconds
```
Checking the logs of the container shows the following:
```
root@1cd712a1af22:/tmp/compose# docker logs -f test_test_1 
Running 0
Running 0
Running 1
Running 2
Running 3
Running 4
Running 5
```
The container is being created (up) and then killed and started again.
The restart happens because of `subscribe`. Removing `subscribe` or replacing it with `require` does not do the restart.
This behaviour is somehow expected but not for the very first creation and start.

## Expected Behavior
When running puppet the first time:
docker-compose.yml is being created and docker-compose up is run to start the container (no restart afterwards!)
When running puppet the second time (while changing docker-compose.yml's content):
Update of docker-compose.yml and restart of the container

## Steps to Reproduce
see above

## Environment
 - /etc/puppetlabs/code/environments/production/modules
└─┬ puppetlabs-docker (v3.7.0)
  ├─┬ puppetlabs-apt (v7.1.0)
  │ └── puppetlabs-translate (v2.0.0)
  ├── puppetlabs-powershell (v2.3.0)
  ├── puppetlabs-reboot (v2.2.0)
  └── puppetlabs-stdlib (v6.0.0)

 - Platform https://hub.docker.com/_/puppet-agent-ubuntu + Fedora 30 on docker host

## Additional Context
I stumbled over this when deploying postgres database in a container, which runs initdb.
Because of the restart happening, initdb is killed which puts da postgres datadir into a broken state and the database will never work.

**Comment by choman** [comment]
following

**Comment by LordVeovis** [comment]
Following.
The issue is that a notify call restart and the current implementation of restart being:

```bash
docker-compose kill
docker-compose build
docker-compose up -d # called by create
```

It should not, instead a notify should IMO be equivalent to:

```bash
#docker-compose kill
#docker-compose build
docker-compose up -d --build # called by create
```

Restarting the whole stack each time one container is modified should not be the preferred way.
