### ISSUE TITLE
Can't pass multiple env parameters to docker::services

### ISSUE THREAD

**Issue by guimaluf** [puppetlabs/puppetlabs-docker#53]
env parameter on  `docker::services` is set to String. In that manner isn't possible to define multiple --env parameters

**Comment by guimaluf** [comment]
Can't pass multiple label parameter neither

**Comment by RXM307** [comment]
@guimaluf labels should have been from commit f316b33

**Comment by guimaluf** [comment]
@RXM307 docker::service**s**
