### ISSUE TITLE
docker_command missing or replaced partially

### ISSUE THREAD

**Issue by kristinchakarov** [puppetlabs/puppetlabs-docker#538]
## Describe the Bug
docker_command parameter seems to be removed from previous versions, but still kept in the template files. However it exists in a weird if statement:

  if ($::osfamily == 'windows') {
    $docker_command                  = 'docker'
  } else {
    $docker_command                  = 'docker'
  }

Basically when you try to set docker_command while running docker class, it says this parameter is not available. Also if you don't set it, the systemd docker attempts to run:
/usr/bin/docker --<params> instead of:
/usr/bin/dockerd --<params>

## Expected Behavior
You should be able to set the variable if it's still present in the templates.

## Steps to Reproduce
Try to set the variable in a puppet environment and you will get error message when loading facts.

## Environment
 - Version Puppetserver 6.7, puppetlabs-docker 3.8.0
 - Platform CentOS 7.6

How I fixed this is:

Added the docker_command variable in init.pp and in params.pp so it can be used. Also commented out the weird if statement above.

**Comment by baurmatt** [comment]
It tend to remove that option and just hardcode the binary name. Is there any actual use case of having this configurable?

**Comment by kristinchakarov** [comment]
In Linux CentOS 7.6 it tried to run the module with /usr/bin/docker which is incorrect. It should run the process with the daemon (/usr/bin/dockerd) otherwise the process never starts, it just hanged for me, so I had to do this change. Even though before I make it editable again I tried to apply dockerd on the variable in the else statement, but it didn't work out.
