### ISSUE TITLE
Implement Pinning of specified Docker version

### ISSUE THREAD

**Issue by jacksgt** [puppetlabs/puppetlabs-docker#548]
## Use Case

Hi,

at the moment it is possible to tell the `puppetlabs-docker` module to install a specific version, which it then correctly does.

When a new Docker version comes out, it will still be offered by `apt` (in our case) as an update:
```
$ apt list --upgradable
docker-ce/buster 5:19.03.4~3-0~debian-buster amd64 [upgradable from: 5:19.03.2~3-0~debian-buster]
```

## Solution
In addition to pinning the upstream repository of Docker, the module should also implement a feature to pin a specific version of Docker (so it won't be automatically upgraded in a cluster, for example).

---

If there is any interest in this feature, I will be happy to provide a PR for it.

**Comment by chelnak** [comment]
Closing as it would appear that this was fixed in #19 :smile:
