### ISSUE TITLE
Unable to install docker-ce 17.06 onwards

### ISSUE THREAD

**Issue by matthanley** [puppetlabs/puppetlabs-docker#564]
## Describe the Bug

#490 has broken ability to install Docker 17.x > 17.05

For example, the regex on https://github.com/puppetlabs/puppetlabs-docker/blob/af994cc3855f3530a2afb396c2e8db7ad97986cb/manifests/init.pp#L597 incorrectly matches `17.12.0~ce-0~debian`, causing Puppet to try and install `docker-engine=17.12.0~ce-0~debian` which does not exist.

## Expected Behavior

Regex should match version 17 only up to 17.05 to allow `docker-ce` to be installed for Docker >=17.06

## Steps to Reproduce

```puppet
	class {'docker':
		version				=> '17.12.0~ce-0~debian'
	}
```

## Environment

Debian Stretch

**Comment by sanfrancrisko** [comment]
Raised [IAC-1039](https://tickets.puppetlabs.com/browse/IAC-1039) to address this
