### ISSUE TITLE
docker-engine install not working on RHEL 7

### ISSUE THREAD

**Issue by scottpecnik** [puppetlabs/puppetlabs-docker#57]
Hey Guys,

We're seeing an issue with this mod (we think) after issue #31 was merged in.  We're running RHEL 7.4 and unfortunately docker-engine 1.12.6.  The issue that just started occurring is with installing docker.  Below is our puppet code (note that we recently switched to this mod from garethr/docker):

```
  class { 'docker':
    docker_users               => ['ouruser'],
    repo_opt                   => '',
    version                    => $version,
    service_overrides_template => false, # Required as Docker module breaks default rhel Docker installation.
    service_config             => false, # Required as Docker module breaks default rhel Docker installation.
    storage_config             => false, # Required as Docker module breaks default rhel Docker installation.
  }
```

With version 1.0.2 of this mod we see the following in our puppet reports:

```
baseurl changed 'https://yum.dockerproject.org/repo/main/centos/7' to 'https://yum.dockerproject.org/repo/main/redhat/7'
Source:	/Stage[main]/Docker::Repos/Yumrepo[docker]/baseurlFile:	/etc/puppetlabs/code/environments/production/modules/docker/manifests/repos.ppLine:	60
```

The old module was setting the baseurl in /etc/yum.repos.d/docker.repo to [https://yum.dockerproject.org/repo/main/centos/7](https://yum.dockerproject.org/repo/main/centos/7), which contains the docker-engine rpm at version 1.12.6.  The update to the mod is setting the baseurl in docker.repo to: [https://yum.dockerproject.org/repo/main/redhat/7](https://yum.dockerproject.org/repo/main/redhat/7).  We do have valid RHEL licenses and our machines are subscribed to Redhat via the subscription manager.

In order to resolve our issue we have reverted the module back to version 1.0.1

Seems this line of code is where the baseurl for the repo is being set:
https://github.com/puppetlabs/puppetlabs-docker/blob/4f46d283f16d3eb05afb75cc32a399aeeb1836ef/manifests/params.pp#L179

Thanks!

**Comment by davejrt** [comment]
Fixed in PR #59
