### ISSUE TITLE
docker-ce-cli is not managed

### ISSUE THREAD

**Issue by vosdev** [puppetlabs/puppetlabs-docker#597]
## Describe the Bug
Installing a specific version of docker-ce will leave you with the latest docker-ce-cli instead of the docker-ce-cli that is supposed to come with that version of docker-ce

## Expected Behavior
Module to manage the version of both docker-ce and docker-ce-cli

## Steps to Reproduce

My example host has
```yaml
docker::version: '5:19.03.6~3-0~debian-buster'
```

result is a 19.03.6 docker daemon and 19.03.8 cli tool
```
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for docker-dev.example.com
Info: Applying configuration version '1586961397'
Notice: /Stage[main]/Docker::Install/Package[docker]/ensure: created
Notice: Applied catalog in 25.11 seconds

~
root @ docker-dev # dpkg -l | grep docker
ii  docker-ce                            5:19.03.6~3-0~debian-buster  amd64        Docker: the open-source application container engine
ii  docker-ce-cli                        5:19.03.8~3-0~debian-buster  amd64        Docker CLI: the open-source application container engine

~
root @ docker-dev # docker --version
Docker version 19.03.8, build afacb8b7f0
```

## Environment
 - Version 3.9.1
 - Platform Ubuntu 18.04

**Comment by voiprodrigo** [comment]
Came here to check for this as well, faced the same issue on Centos 7 and docker-ce 19.03.15 (cli remained at .12).

**Comment by stefanlasiewski** [comment]
Same thing here. Ubuntu 18.04.

```
# apt list --installed docker\* 
Listing... Done
docker-ce/bionic,now 5:19.03.14~3-0~ubuntu-bionic amd64 [installed]
docker-ce-cli/bionic,now 5:20.10.2~3-0~ubuntu-bionic amd64 [installed,automatic]
```

I don't remember what Docker's supported version skew is, but this might violate that.
