### ISSUE TITLE
Systemd unit file template contains impossible to reach option "StartLimitBurst=5"

### ISSUE THREAD

**Issue by omeinderink** [puppetlabs/puppetlabs-docker#615]
## Describe the Bug
The file templates/etc/systemd/system/docker-run.erb contains these three Systemd unit file options:
```
[Unit]
StartLimitIntervalSec=20
StartLimitBurst=5
[Service]
RestartSec=5
```
These numbers make no sense: if a service fails Systemd will wait for 5 seconds before restarting it. That amounts to a maximum number of 4 restarts every 20 seconds. StartLimitBurst will prevent the service from being restarted more than 5 times in 20 seconds (per StartLimitIntervalSec=20), which accordingly will never happen.

The result is that a failing service will never stop restarting as it never reaches the limit.

## Expected Behavior
A failing service eventually is in "failed" status in Systemd

## Steps to Reproduce
Create an intentionally failing service by editing the script created by the module at
`/usr/local/bin/docker-run-<%= @sanitised_title %>-start.sh`
and adding
`exit 1`
after the shebang line, then restart the service via Systemd. The service will never stop restarting.

## Environment
- Ubuntu 18.04

**Comment by chelnak** [comment]
Closing as it looks like this was fixed in #616 :smile:
