### ISSUE TITLE
docker::registry: Allow password to be provided as a hash

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/puppetlabs-docker#62]
`pw_hash` has issues with FIPS systems ([MODULES-6135](https://tickets.puppetlabs.com/browse/MODULES-6135)), so I would like to be able to provide a password as a hash to skip the `pw_hash` function. 

The line https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/registry.pp#L71, which specifies SHA-512, still fails on `pw_hash` (weird). 

My test environment can be replicated by cloning [simp/simp_docker](https://github.com/simp/pupmod-simp-simp_docker), installing the gems etc, and running `BEAKER_fips=yes BEAKER_destroy=no rake 'beaker:suites[redhat]'`. It should fail on this line: https://github.com/simp/pupmod-simp-simp_docker/blob/master/spec/acceptance/suites/redhat/30_registry_spec.rb#L81

**Comment by scotty-c** [comment]
Hi @jeefberkey,
This seems to be a fringe use case. We won't be prioritising this into the next few sprints. In saying that we are more than happy to look at a PR if you would like to raise one.

**Comment by jeefberkey** [comment]
No problem, I will see what I can come up with.
