### ISSUE TITLE
[3.9.1] facter bug using podman

### ISSUE THREAD

**Issue by tuxmaster5000** [puppetlabs/puppetlabs-docker#639]
When podman-docker is installed on the system, than puppet facts fails with:
Error: Facter: error while resolving custom fact "docker_client_version": undefined method `[]' for nil:NilClass
None of docker code from the module is used, but facts code are distributed about all nodes. 

OS: CentOS 7.8
docker version --format '{{json .}}'
returns:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
{
    "RemoteAPIVersion": 1,
    "Version": "1.6.4",
    "GoVersion": "go1.12.12",
    "GitCommit": "",
    "Built": 0,
    "OsArch": "linux/amd64"
}
```

**Comment by vosdev** [comment]
I'd say the problem here is podman, not this module.

You're telling podman to output in json and 
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
{
...
}
```
is invalid json. From the looks of it you can suppress that message by creating `/etc/containers/nodocker`

**Comment by tuxmaster5000** [comment]
I think the plug in must detect that it podman and not docker.
