### ISSUE TITLE
Unknown resource type: 'apt::source'

### ISSUE THREAD

**Issue by madisonleavo** [puppetlabs/puppetlabs-docker#64]
This is my first go at using managing Docker with Puppet, so I could be doing something obviously wrong! But, when trying use/setup docker on Ubuntu 16.04 client I get:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, 
Unknown resource type: 'apt::source' at /etc/puppetlabs/code/environments/dev/modules/docker/manifests/repos.pp:23:9 on node X
```

Puppetfile:

```
forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
# Versions should be updated to be the latest at the time you start
mod "puppetlabs/inifile",     '1.5.0'
mod "puppetlabs/stdlib",      '4.11.0'
mod "puppetlabs/concat",      '2.1.0'
mod 'puppetlabs-docker', '1.0.2'
mod 'puppetlabs-apt', '3.0.0'
mod 'stahnma-epel', '1.3.0'
```

Manifest common.pp:
```
class profile::docker::common (
  ) {
  include docker
   }
```

**Comment by davejrt** [comment]
Hi

At this point the docker module has a dependency on apt 2.1.0

`"dependencies": [
    {"name":"puppetlabs/stdlib","version_requirement":">= 4.1.0"},
    {"name":"puppetlabs/apt","version_requirement":">= 2.1.0"},
    {"name":"stahnma/epel","version_requirement":">= 0.0.6"}
  ],`

We are working on removing this to an up to date version however for the time being you'll need to use v 2.1.0

**Comment by davejrt** [comment]
Hi

apt 3.0.0 has a dependency on stdlib (>= 4.16.0 < 5.0.0), so I'd suggest validating that before looking any further at the docker module.

**Comment by madisonleavo** [comment]
Thank you! I fixed the version numbers and that did not help my error.

I'm using the latest Docker version 17.09.0~ce-0~ubuntu and I think what ended up being the issue was   I needed to manually set some params--I couldn't just `include docker`

The key for me was setting param `use_upstream_package_source => false,` that fixed the error `Unknown resource type: 'apt::source'`

But then other errors surface. The final, mostly-working-enough version:
```
class profile::docker::common (
  String $package_name = 'docker-ce',
  String $docker_command = 'dockerd',
  String $daemon_subcommand = '-H fd://',
  ) {
  case $::osfamily {
    'Debian':{
      class { 'docker':
		    use_upstream_package_source => false,
		    package_name => $package_name,
		    version => '17.09.0~ce-0~ubuntu',
		    docker_command => $docker_command,
		    daemon_subcommand => $daemon_subcommand,
	    }
    }
    'RedHat':{
      #na
    }
  }
}
```
There is some weirdness associated with needing the socket opened in another systemd file (in Centos for sure), but I'll open another ticket for that :) Thanks for setting me on the right path.

**Comment by davejrt** [comment]
I've just tested this with the following puppetfile
`#!/usr/bin/ruby env

require "socket"
$hostname = Socket.gethostname

forge 'http://forge.puppetlabs.com'

mod "puppetlabs/inifile",     '1.5.0'
mod "puppetlabs/stdlib",      '4.16.0'
mod "puppetlabs/concat",      '2.1.0'
mod 'puppetlabs-docker', '1.0.2'
mod 'puppetlabs-apt', '3.0.0'
mod 'stahnma-epel', '1.3.0'`

with `include docker`

On the `puppetlabs/ubuntu-16.04-64-puppet` vagrant box without issue. I suspect you might have some other environmental factors at play here. 

If you're not already on it, I recommend the puppet community slack as a good place to seek advice from others. You can find me on there.

**Comment by madisonleavo** [comment]
Thanks so much for your time and advice! I will join.
