### ISSUE TITLE
Request: allow puppetlabs-powershell < 5.0.0 & puppetlabs-reboot < 4.0.0

### ISSUE THREAD

**Issue by rauschbit** [puppetlabs/puppetlabs-docker#658]
## Use Case
Please allow the module version v4.0.0 dependency for [puppetlabs-powershell](https://forge.puppet.com/modules/puppetlabs/powershell) because there is a bug fixed there regarding the following powershell.rb
- https://github.com/puppetlabs/puppetlabs-powershell/blob/83f5d821ca2f62ea15ac94735239d0c2ee5b4d55/lib/puppet/provider/exec/powershell.rb
- https://tickets.puppetlabs.com/browse/MODULES-10539

![image](https://user-images.githubusercontent.com/8775595/101631946-75d49880-3a25-11eb-9aa5-399b88271337.png)

Please also allow the module version v3.1.0 dependency for [puppetlabs-reboot](https://forge.puppet.com/modules/puppetlabs/reboot)
![image](https://user-images.githubusercontent.com/8775595/101632135-b9c79d80-3a25-11eb-9347-0017df94cd2a.png)

## Describe the Solution You Would Like
Please allow `< 5.0.0` for puppetlabs-powershell for this module
Please allow `< 4.0.0` for puppetlabs-reboot for this module

## Describe Alternatives You've Considered
For the last half year we copied [this script](https://github.com/puppetlabs/puppetlabs-powershell/blob/83f5d821ca2f62ea15ac94735239d0c2ee5b4d55/lib/puppet/provider/exec/powershell.rb) (released in February 2020) manually to our puppetlabs-powershell module which isn't a real solution...

**Comment by rauschbit** [comment]
I don't want to stress anyone but is here someone who takes care of this?

**Comment by rauschbit** [comment]
It seems that no one cares... 👎

**Comment by arcenik** [comment]
Here it is : https://github.com/puppetlabs/puppetlabs-docker/pull/719

**Comment by rauschbit** [comment]
Many thx for this Merge! Hopefully there is a release in v3.13.2 or so soon.

**Comment by chelnak** [comment]
Closing as this seems to have been resolved by #722 and #723! Thanks for opening the issue :smile:
