### ISSUE TITLE
Containsers fail to `run` when command supplied at 3.12.0

### ISSUE THREAD

**Issue by rafaltrojniak** [puppetlabs/puppetlabs-docker#661]
## Describe the Bug
When the `docker::run` is used with `command` option, there is additional space forced at the beginning of the command.

## Expected Behavior
There should not be additional spaces forced before the command

## Steps to Reproduce
Use following module
```
docker::run {'test':
  image => 'alpine/edge',
  command => 'sh',
}
```
This will fial as ` sh` is not found. It should start the container

## Environment
 - Version 3.12.0
 - Platform Linux
## Additional Context
I bet ths is caused by that line change https://github.com/puppetlabs/puppetlabs-docker/blob/main/templates/docker-run-start.erb#L15
changed in f9f80c5b0725810ae84dc9651f9503d821e77144 .

The backslash `\` should not be there.

**Comment by shamil** [comment]
I believe https://github.com/puppetlabs/puppetlabs-docker/pull/652 is what caused the bug
