### ISSUE TITLE
docker::registry fails if $version is not explicitly set

### ISSUE THREAD

**Issue by hex2a** [puppetlabs/puppetlabs-docker#68]
puppet version: **4.10.9**
module version: **1.0.2**

```
Error while evaluating a Resource Statement, Evaluation Error: Left match operand must result in a String value. Got an Undef Value. at /etc/puppetlabs/code/environments/production/modules/docker/manifests/registry.pp:47:74
```

`$version` is set to `undef` in params.pp:
https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/registry.pp#L43
https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/params.pp#L6

**Comment by davejrt** [comment]
Can I get some more information, including your OS, manifest, any hiera entries your passing in? As well more of the log file run in debug/verbose.

We cover off this scenario in our acceptance tests and I can't replicate in a quick local test.

**Comment by jarretlavallee** [comment]
This can be seen on Ubuntu 16.4 and 14.04 when using docker::registry. The agent fails [here](https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/registry.pp#L53) when comparing the Undef `version` parameter as `$version =~ /1[.][1-9]0?/`.

Below is the output from 1.0.2:

~~~
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Left match operand must result in a String value. Got an Undef Value. at /etc/puppetlabs/code/environments/development/modules/docker/manifests/registry.pp:47:74
~~~

**Comment by davejrt** [comment]
I'm still yet to find a scenario where I can replicate this. Can you send me your node defintion? If I install the module like so, I can't replicate that behaviour. This is on Ubuntu 16.04 and centos 7

`  class {'docker':}

  docker::run {'registry':
    image => 'registry',
    pull_on_start => true,
    ports         => '5000:5000',
    volumes       => '/tmp/registry-dev',
  }

  docker::registry {'localhost:5000':
    username => 'username',
    password => 'password',
  }`

**Comment by jarretlavallee** [comment]
@davejrt Thanks for looking into this. It only occurs when `docker::registry::username`, `docker::registry::password` and `docker::registry::email` are not Undef. Using your example with the `email` parameter, I am able to reproduce the issue. In looking at the code, it looks like it is not dependent on the OS, so it should occur on Centos too. 

~~~
class {'docker':}

  docker::run {'registry':
    image => 'registry',
    pull_on_start => true,
    ports         => '5000:5000',
    volumes       => '/tmp/registry-dev',
  }

  docker::registry {'localhost:5000':
    username => 'username',
    password => 'password',
    email        => 'email@email.com',
  }
~~~

Outputs the following. 

~~~
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Left match operand must result in a String value. Got an Undef Value. at /etc/puppetlabs/code/environments/production/modules/docker/manifests/registry.pp:47:74  at /root/docker.pp:10 on node tchm9hn78c8weh7.delivery.puppetlabs.net
~~~

**Comment by davejrt** [comment]
OK cool

So I suppose the assumption made when developing this was, that you wouldn't be passing email without defining the version, because this flag was deprecated after docker v1.10. 

So I would expect that if you're not using an older version, and we changed the logic to say 
`    if $username != undef and $password != undef and $email != undef and ( $version =~ /1[.][1-9]0?/ or $version != undef ) {
`

then you would get an error like so

`
Error: /Stage[main]/Main/Node[default]/Docker::Registry[localhost:5000]/Exec[localhost:5000 auth]: Failed to call refresh: 'docker login -u 'username' -p "${password}" -e 'test@test.com' localhost:5000' returned 125 instead of one of [0]
`

So in order to actually use the email flag to actually have any effect you need to be using an older version, otherwise the if statement below it is what is actually being executed

**Comment by jarretlavallee** [comment]
Ok, that makes sense. For users that may still have the email parameter defined and upgrade the module, it will fail with the comparison error. Do you think we could add the `$version != undef ` and a warning about the deprecation of the email parameter?

Thanks!

**Comment by davejrt** [comment]
We've had an internal discussion and we are going to leave the code as is, but we'll add specific code examples to the README for this define type, as well as a link to the docker change log as a reference. 

Feel free to reach out on the puppet slack if you'd like to discuss further
