### ISSUE TITLE
Sponsor project

### ISSUE THREAD

**Issue by ahoiroman** [puppetlabs/puppetlabs-docker#691]
Hello,

as I am using this module in commercial projects, I depend on regular updates and ongoing support. GitHub introduced sponsorship campaigns for projects a while ago. I would be happy to spend a few dollars, so maybe other users would do that too. Could be worth considering this... :-)

**Comment by binford2k** [comment]
Hey @ahoiroman! We'd rather just know that you're a happy user and invite you to collaborate in the community (slack.puppet.com) if you ever feel so inclined. Send your details to community@puppet.com if you'd like a t-shirt.
