### ISSUE TITLE
Security risk using /var/tmp as HOME

### ISSUE THREAD

**Issue by sdinten** [puppetlabs/puppetlabs-docker#699]
## Description
The fix for #689 is using the path /var/tmp as home folder.
This folder is writable by everybody.

This could have security impact:
Regarding https://docs.docker.com/engine/reference/commandline/cli/ :
By default, the Docker command line stores its configuration files in a directory called .docker within your $HOME directory. Docker manages most of the files in the configuration directory and you should not modify them. However, you can modify the config.json file to control certain aspects of how the docker command behaves.

So every user could invoke changing of docker settings by creating config in /var/tmp/.docker/

@sebastianTC thanks for mentioning this!

## Expected Behavior
Everything works as expected but there is a security risk 

## Steps to Reproduce
Run puppet agent with an environment that uses the docker module

## Environment
All

**Comment by sdinten** [comment]
Already fixed... https://github.com/puppetlabs/puppetlabs-docker/pull/698/files

**Comment by intgr** [comment]
Was the insecure behavior ever part of any Docker release?

**Comment by sdinten** [comment]
No, looking at the tag for 3.13.0 I can see that '/root' was already put in
before the release was made.

https://github.com/puppetlabs/puppetlabs-docker/compare/v3.13.0...main

**Comment by sebastianTC** [comment]
@sdinten :

Sorry this isn't right.
The changes you see on your link, are the changes which were merged to the main branch after the release.

So yes the issue is still part of the current release.

**Comment by sdinten** [comment]
@sebastianTC  you're right (again). It seems that PR https://github.com/puppetlabs/puppetlabs-docker/pull/698 (already merged) did not make it into the release. @adrianiurca can you put this pull request in the following update?

**Comment by sdinten** [comment]
Fixed as of 3.13.1 (PR #698)
