### ISSUE TITLE
 Unable to locate package linux-image-extra-4.4.0-1041-aws on Amazon EC2 Ubuntu 16.04

### ISSUE THREAD

**Issue by drscre** [puppetlabs/puppetlabs-docker#70]
I am trying to install docker on Amazon EC2 machine which is launched from Ubuntu 16.04 ami, but get the following error:

`Unable to locate package linux-image-extra-4.4.0-1041-aws`

This happens because there is no such package for AWS Ubuntu 16.04 kernel. 
Even more, this package is not required, because aufs driver was moved to the linux-aws kernel package itself (https://github.com/docker/docker.github.io/issues/2694)

**Comment by shamil** [comment]
set `manage_kernel => false`

**Comment by drscre** [comment]
I ended up using `manage_kernel => false`
Will close this issue because it seems there is little sense in trying to automatically detect whether we are running on aws kernel or not
