### ISSUE TITLE
Duplicate declaration statement: docker_params_changed is already declared

### ISSUE THREAD

**Issue by ahoiroman** [puppetlabs/puppetlabs-docker#714]
## Describe the Bug
`puppet agent --test` throws 

> Duplicate declaration statement: docker_params_changed is already declared at (file: /etc/puppetlabs/code/environments/production/modules/docker/manifest/run.pp, line 470)

## Expected Behavior
No error on execution

## Environment
 - Version 1.3.1
 - Platform CentOS7

**Comment by simmerz** [comment]
I have the same issue. I have two profiles with `docker::run` statements which are the duplicate declarations that are being complained about. If I use both of them at the same time on the same machine, I see this error.

**Comment by basti-nis** [comment]
This Problem occurs since module Version 3.13.1.

Maybe something like this can help:
`run.pp` from
```
473        notify { 'docker_params_changed':
474          message  => $detect_changes,
475        }
```
to
```
473        notify { "${title}_docker_params_changed":
474          message  => $detect_changes,
475        }
```
