### ISSUE TITLE
Don't break systemd::dropin_file for Docker

### ISSUE THREAD

**Issue by ace13** [puppetlabs/puppetlabs-docker#72]
With the docker module in place, attempting to add a systemd dropin file like;
```puppet
systemd::dropin_file { '10-docker-proxy.conf':
  ensure  => file,
  content => epp("${module_name}/proxy/systemd-environment.epp", {
      host_fqdn => $host_fqdn,
      host_port => $proxy_host[parameters][port],
      proxy     => $proxy,
      no_proxy  => $no_proxy,
  }),
  unit    => 'docker.service',
}
```

Will cause compilation errors like;
`Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Duplicate declaration: File[/etc/systemd/system/docker.service.d] is already declared in file /etc/puppetlabs/code/environments/production/modules/docker/manifests/service.pp:150; cannot redeclare at /etc/puppetlabs/code/environments/production/modules/systemd/manifests/dropin_file.pp:52 at /etc/puppetlabs/code/environments/production/modules/systemd/manifests/dropin_file.pp:52:5 at /etc/puppetlabs/code/environments/production/modules/profiles/manifests/proxy/client.pp:27 on node example.com`

**Comment by davejrt** [comment]
Hi

I'll review this with the team and see what we can come up with.

**Comment by ace13** [comment]
Worth noting is that [their implementation](https://github.com/camptocamp/puppet-systemd/blob/master/manifests/dropin_file.pp#L50-L56) already uses `ensure_resource`, so perhaps the `if ! defined` pattern might be better applied against this module.
```puppet
  if $ensure != 'absent' {
    ensure_resource('file', "${path}/${unit}.d", {
      ensure => directory,
      owner  => 'root',
      group  => 'root',
    })
  }
```
