### ISSUE TITLE
Services fail to start after Docker update to 20.10.4

### ISSUE THREAD

**Issue by markvr** [puppetlabs/puppetlabs-docker#727]
This is a bug in Docker not this Puppet module but I thought I'd raise this for visibility here because it manifests when using this module and is a major issue.

See https://github.com/moby/moby/issues/42101

On Docker 20.10.4, when doing a `docker create` then `docker start -a ...`  your services will just hang when starting.   `docker run`  seems unaffected, but the `systemd` scripts this module generates do `create` & `start` and so any services managed by this Puppet module will fail to run after updating to Docker 20.10.4.

**Comment by bkuebler** [comment]
New version available since 2021-03-02 it looks like it works again. They reverted https://github.com/docker/cli/pull/2960 see https://docs.docker.com/engine/release-notes/#20105
