### ISSUE TITLE
Is it possible to set "registry-mirrors" for Docker daemon?

### ISSUE THREAD

**Issue by oryagel** [puppetlabs/puppetlabs-docker#73]
Is it possible to use registry-mirrors with this module?

From the docs:
```Either pass the --registry-mirror option when starting dockerd manually, or edit /etc/docker/daemon.json and add the registry-mirrors key and value, to make the change persistent.```

https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon

**Comment by davejrt** [comment]
Hi

We'll create a ticket for this and look at supporting it in an upcoming release. If this is something you require urgently we're more than happy to take PR's on this module from the community.

**Comment by davejrt** [comment]
@oryagel just an update that this is being actively worked on this sprint

**Comment by davejrt** [comment]
Closed in PR #109
