### ISSUE TITLE
Add support for AmazonLinux 2

### ISSUE THREAD

**Issue by PolaricEntropy** [puppetlabs/puppetlabs-docker#747]
## Use Case
I'm using AmazonLinux 2 on Puppet nodes I want to use this module. That used to work before [PR 667](https://github.com/puppetlabs/puppetlabs-docker/pull/667).

## Describe the Solution You Would Like
If os.family is RedHat, but name is Amazon then skip the version requirement.

## Describe Alternatives You've Considered
The current solution is to use 3.12.1, which makes us miss out on improvements.

## Additional Context
 AmazonLinux 2 is REHL 7 and thus has the os.family fact set to RedHat. Since the release version numbers describe the OS version it's in our AMI set to 2.2 which triggers a version check error.

**Comment by djtecha** [comment]
Any update on this? Appears that everything else works for us using docker_compose we just have to comment out that fail condition. Tried overriding using the acknowledge_unsupported_os = true to also bypass it but gets caught on line #488 in the init.pp file

**Comment by adrianiurca** [comment]
Currently we are not supporting Amazon Linux 2, but we could try to add compatibility for AmazonLinux 2.

**Comment by PolaricEntropy** [comment]
Made #788 to make the acknowledge_unsupported_os setting allow Amazon Linux 2. Allows us to use the module there even though it's not officially supported yet.
