### ISSUE TITLE
docker::run memory_limit sets a seemingly invalid default value

### ISSUE THREAD

**Issue by ALTinners** [puppetlabs/puppetlabs-docker#748]
Docker's documentation for the `-m` command states

> The maximum amount of memory the container can use. If you set this option, the minimum allowed value is 4m (4 megabyte).

https://docs.docker.com/config/containers/resource_constraints/

However `docker::run` defaults this (optional) argument to a defined value of `0b`

https://github.com/puppetlabs/puppetlabs-docker/blob/b8b0b85213e088137196e5304cac0b4f8495808d/manifests/run.pp#L197

Is there a reasoning as to why this value is set to an apparently invalid number vs leaving it as `undef`? Especially given its already optional

As far as I can tell - Docker is simply ignoring this specified constraint (I have plenty of containers that happily eat several MB of memory) - however that could change and many containers deployed using this module could unexpectedly break.

**Comment by Vincevrp** [comment]
I'm using podman-docker (#562) and this default value prevents containers from starting. Podman is unable to start the container and reports:  `Error: OCI runtime error: unable to start container fcd02362087d56b8829dbf4050c8106985733d06c690720ccbfbe3754323eb9e: sync socket closed`.

The kernel (obviously) complains about `Memory cgroup out of memory`

**Comment by kenyon** [comment]
reopen
