### ISSUE TITLE
Support for default-address-pools configuration

### ISSUE THREAD

**Issue by FredPraca** [puppetlabs/puppetlabs-docker#756]
For user generated networks, the automatically defined network can overlap an existing one.
User defined network addresses pool can be provided to Docker daemon through the use of default-address-pools parameter on command line or in _daemon.json_ configuration file (see the [Dockerd configuration](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)). 

Adding an array of map to the _docker::params_ class would be useful to set this inside daemon configuration file.

As a workaround, this can be done through _extra_parameters_ by giving _--default-address-pool_ command line parameter.

**Comment by mpdude** [comment]
Came here looking for a way to configure this. 

@FredPraca Thank you Sir!

**Comment by FredPraca** [comment]
Keep alive :)
