### ISSUE TITLE
Deferred functions failing with certain catalogs

### ISSUE THREAD

**Issue by cedws** [puppetlabs/puppetlabs-docker#761]
This does not strictly relate to this module, but I spent almost a whole day today debugging why trying to start a container using this module wasn't working.  It seems worth it to raise a sort of tracking issue on the off chance that somebody else experiences this and searches Issues.

To summarise, the `Deferred('docker_params_changed', ...)`  function call responsible for changing a container's state when it doesn't match the desired state was having no effect because elsewhere in our catalog there was binary data, causing `puppetserver` to instead serialise to PSON format and making `Deferred` not work at all. Apparently this affects `Sensitive` too but I haven't noticed any issues surrounding that. This issue is described in [PUP-10928](https://tickets.puppetlabs.com/browse/PUP-10928).

I actually had a VM for testing catalogs in which spinning up the container was working. It just wasn't working on our production machine. Eventually it unfolded that this was because I had commented out some code locally that I didn't want to apply to my VM. That code introduced the binary data which triggers this bug. Completely unrelated, independent code.

When it ran successfully in my VM, I'd see `Param changed` proving that the `Deferred` function had actually executed.
```
Notice: /Stage[main]/Profile_unit::Mymanifest/Docker::Run[mymanifest]/Notify[docker_params_changed]/message: defined 'message' as 'Param changed'
```

But on the production machine, I'd see the actual parameters to the `Deferred` function call print out.
```
(/Stage[main]/Profile_unit::Mymanifest/Docker::Run[mymanifest]/Notify[docker_params_changed]/message) defined 'message' as 'Deferred({\'name\' => \'docker_params_changed\', \'arguments\' => [{\'sanitised_title\' => \'mycontainer\', \'osfamily\' => \'Debian\', \'command\' => "docker run -d -u \'root\' \\\n-m 0b \\\n-p 8000:80 \\\n --name mycontainer --cidfile=/var/run/docker-mycontainer.cid --restart=\"always\" mycontainer:latest", \'cidfile\' => \'/var/run/docker-mycontainer.cid\', \'image\' => \mycontainer:latest\', \'volumes\' => [], \'ports\' => \'8000:80\', \'stop_wait_time\' => 0, \'container_running\' => true}]})'
```

We have worked around this issue by removing the binary data and the relevant resources (we didn't actually need the resources as it turns out).

**Comment by adrianiurca** [comment]
Will gonna migrate from deferred functions to resource API and hope this problem will dissapear.
