### ISSUE TITLE
Please migrate away from apt::key

### ISSUE THREAD

**Issue by zeha** [puppetlabs/puppetlabs-docker#766]
## Use Case

Compatibility with future Ubuntu and Debian versions (Ubuntu > 22.04, Debian > 11).

## Describe the Solution You Would Like

Apt::key is deprecated, as it uses the deprecated `apt-key(8)` program under the hood.

Please switch to dropping files into `/etc/apt/trusted.gpg.d` instead.

## Describe Alternatives You've Considered

Maybe apt::key could be switched to do this transparently, but I guess thats unlikely because it would need gpg? (And one point of removing apt-key is ... to make gpg optional.)

**Comment by kenyon** [comment]
Here is the related bug report on the apt module: https://tickets.puppetlabs.com/browse/MODULES-9695

**Comment by zeha** [comment]
I was informed today that dropping an ascii-armored key into trusted.gpg.d should also work.

**Comment by johanfleury** [comment]
I guess you’re referring to [MODULES-9695](https://tickets.puppetlabs.com/browse/MODULES-9695) in which I gave this example. I made a bunch of suggestions in this ticket, but creating a PR is just too much work for me (especially as the PR will effectively be a copy/paste of `archive` code).

I ended up creating a class to manage apt keyrings, here is the full code:

```
# @summary
#   Download and dearmor a GPG keyring in /usr/share/keyrings/
#
define profile::base::apt::keyring(
  Enum['present', 'absent'] $ensure   = 'present',
  String                    $filename = "${title}-keyring.gpg",
  Optional[String]          $source   = undef,
  Optional[String]          $content  = undef,
) {
  if !($content or $source) {
    crit('No content nor source specified')
  } elsif ($content and $source) {
    fail("Profile::Base::Apt::Keyring['${title}']: Can't use 'source' and 'content' at the same time.")
  }

  if $content or $source =~ /^puppet:/ {
    file { "/tmp/${filename}":
      ensure  => file,
      owner   => 'root',
      group   => 'root',
      mode    => '0644',
      content => $content,
      notify  => Exec["gpg --dearmor ${filename}"],
    }

    exec { "gpg --dearmor ${filename}":
      provider    => 'shell',
      cwd         => '/usr/share/keyrings/',
      command     => "gpg --dearmor < /tmp/${filename} > ${filename}",
      refreshonly => true,
    }
  }

  if $source {
    archive { "/tmp/${filename}":
      ensure          => $ensure,
      source          => $source,
      extract         => true,
      extract_path    => '/usr/share/keyrings/',
      extract_command => "gpg --dearmor < %s > ${filename}",
      creates         => "/usr/share/keyrings/${filename}",
    }
  }
}
```
