### ISSUE TITLE
Unknown variable: 'docker::docker_ee_key'

### ISSUE THREAD

**Issue by mpepping** [puppetlabs/puppetlabs-docker#77]
puppetlabs/docker:1.0.2 logs a warning on `docker::docker_ee_key` during compilation.

```
[puppetserver] Puppet Unknown variable: 'docker::docker_ee_key'. at /var/[..]/modules/docker/manifests/init.pp:538:23
```

https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/init.pp#L543

**Comment by davejrt** [comment]
Thanks for your contribution
