### ISSUE TITLE
Need to be able to specify parameters to the image

### ISSUE THREAD

**Issue by daveseff** [puppetlabs/puppetlabs-docker#777]
## Use Case
I need to be able to run the equivalent:
```Docker run -e "SOMEVAR=someval" --name my_container  myimage:latest -option_a some param -option_b someotherparam``` 

## Describe the Solution You Would Like
A parameter to ```docker::run``` like ```container_options => ['-option_a param', '-option_b someotherparam']``` that then gets appended to the docker run command.

Tried using ```extra_parameters``` but those are placed before the image name and produces the "unknown shorthand flag" error when the service runs.

**Comment by adrianiurca** [comment]
That is interesting. But this will require quite effort to implement.
