### ISSUE TITLE
Support for install from Mirantis or Moby?

### ISSUE THREAD

**Issue by Hvid** [puppetlabs/puppetlabs-docker#786]
## Use Case
Does this module support install on Windows Server 2022 from Mirantis or Moby instead of DockerMsftProvider?

## Describe the Solution You Would Like
As Microsoft has deprecated the DockerMsftProvider from sometime next year, I need a way to install from Mirantis or Moby instead:
https://docs.mirantis.com/mcr/20.10/install/mcr-windows.html
Or from moby directly.

I would of course like this to be managed by puppet in the same way as today if possible. Maybe this is already supported, if so please show me how :)

## Describe Alternatives You've Considered
Manual install instead of puppet :(

## Additional Context
https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799

**Comment by slonopotamus** [comment]
You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install Docker for Windows containers on both Windows Server/Client.

**Comment by jpatigny** [comment]
+1

**Comment by jpatigny** [comment]
Another solution might be to use the chocolatey package to install it.

Choco package : https://community.chocolatey.org/packages/docker-engine

Example : 

```
include chocolatey

package { 'docker-engine':
  ensure   => '20.10.11',
  provider => 'chocolatey',
}
```

**Comment by slonopotamus** [comment]
> Another solution might be to use the chocolatey package docker-engine to install it.

Besides dockerd, you would want docker cli. There is [docker-cli](https://community.chocolatey.org/packages/docker-cli) chocolatey package, but it wasn't updated since 2020. There also exists [docker](https://community.chocolatey.org/packages/docker) package, but it was deprecated in favor of `docker-cli` in 2019.

**Comment by jpatigny** [comment]
FYI docker-cli choco package is now maintained again : https://community.chocolatey.org/packages/docker-cli

**Comment by chelnak** [comment]
@Hvid Thank you for opening this issue.

While we agree this is likely an improvement, we do not anticipate addressing this as it represents a technical direction that we have decided not to follow at.

As such, this issue will be closed. 

However, we may revisit this at a later time, and if so, will reference this ticket.

In the meantime, it looks like there are a couple of good alternative suggestions above.
