### ISSUE TITLE
using Packages from Debian Repository fails with missing docker-ce-cli package

### ISSUE THREAD

**Issue by peterbeck** [puppetlabs/puppetlabs-docker#797]
When using the Debian repo (use_upstream_pacakge_source => false) the module is trying to install docker-ce-cli, which is not available in the Debian repositories. There is just 'docker.io'. 
This only happens when using puppetlabs-docker > 4.0.1

```
E: Package 'docker-ce-cli' has no installation candidate
Error: /Stage[main]/Docker::Install/Package[docker-ce-cli]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install docker-ce-cli' returned 100: 
...
Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

I know Debian 11 is officially not on the supported OS list... and I'd like to use the packages from the official Debian repository.

## Expected Behavior
With [puppetlabs-docker 4.0.1](https://github.com/puppetlabs/puppetlabs-docker/releases/tag/v4.1.0) everything works as expected. I think this issue was introduced with #740.

## Steps to Reproduce
1. install puppetlabs-docker > 4.0.1
2. run puppet with this configuration:
```
class { 'docker':
   use_upstream_package_source => false,
   service_overrides_template  => false,
   docker_ce_package_name      => 'docker.io',
}
```
is there a way to get around this issue and using the latest module version ? 
Or am I doing something wrong ?

Thanks and regards
Peter

## Environment
 - puppetlabs-docker >= 4.1.0
 - Debian 11.2 / Bullseye
 - puppet agent 7.14.0
 - puppetserver 7.6.0

**Comment by kenyon** [comment]
I'd guess we need to remove https://github.com/puppetlabs/puppetlabs-docker/blob/main/manifests/install.pp#L83-L86 and the test for that.

**Comment by vchepkov** [comment]
Same problem exists on RHEL as well, manifests tries to install package even if docker-ce is not used

**Comment by chelnak** [comment]
I think this PR should fix it.

https://github.com/puppetlabs/puppetlabs-docker/pull/798
