### ISSUE TITLE
Permission denied from mkdir /tmp_docker in v4.2.0

### ISSUE THREAD

**Issue by kenyon** [puppetlabs/puppetlabs-docker#819]
With v4.2.0 of this module, I get `Permission denied - /tmp_docker` from a puppet agent run.

Caused by #805: https://github.com/puppetlabs/puppetlabs-docker/pull/805/files#r847521695

**Comment by r-catania** [comment]
We are seeing the same behavior with 4.2.0 

` error during compilation: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/docker_compose: Could not autoload puppet/provider/docker_compose/ruby: Permission denied @ dir_s_mkdir - /tmp_docker`

**Comment by canihavethisone** [comment]
I have commented on the pull request.  Requested investigation.

**Comment by chelnak** [comment]
Hey all! Thanks for raising this. It's certainly strange that this has popped up. It's not something that we observed initially.

We will spin up a lab today and attempt to reproduce the issue.

Thanks!!

**Comment by canihavethisone** [comment]
Sounds like a good approach.  I'll check a CIS hardened system in a few mins with regard to the exec bit on the suggested /var/tmp.  I also observed that the temporary files created by docker-compose are cleaned up after it runs.

**Comment by canihavethisone** [comment]
i use a slim wrapper such as:
`
class roles::test (
  $composefiles = lookup( 'test::composefiles',    Optional[Hash],  'deep', {} ),
  $compose_defs = lookup( 'test::compose_defs',    Optional[Hash],  'deep', {} ),
){

  # Include the main docker class
  class { 'docker':
    log_driver => 'journald',
  }

  # Include classes as listed in hiera
  hiera_include('classes')

  # Create docker-compose files
  $composefiles.each  |$key, $value| {
    file { $key:
      * => $value
    }
  }

  # Process docker-compose resources
  $compose_defs.each  |$key, $value| {
    docker_compose { $key:
      * => $value
    }
  }

  # Ensure that iptables is installed before docker
  Package <| title == 'iptables' |> -> Package <| title =='docker' |>

  # Ensure that firewall chains and rules created by docker are not purged
  Resources <| title == 'firewall' |> { purge => false }

  # Ensure that images are built, then containers run, then docker compose
  Docker::Image <| |> -> Docker::Run <| |> -> Docker_compose <| |> 

}
`

with hiera such as:
`
---
classes:
  - docker::compose

test::compose_defs:
  test:
    compose_files: ['/tmp/composefile1.yaml']
    subscribe:     'File[/tmp/composefile1.yaml]'
    ensure:        present
    scale:
      db:        1
      wordpress: 1      
  test2:
    compose_files: ['/tmp/composefile2.yaml']
    subscribe:     'File[/tmp/composefile2.yaml]'
    ensure:        present
    scale:
      my_test:    1
      my_test_2:  2
      redis:      3
      postgres:   4


test::composefiles:
  /tmp/composefile1.yaml:
    source: 'http://192.168.1.60/composefile1.yaml'
  /tmp/composefile2.yaml:
    source: 'http://192.168.1.60/composefile2.yaml'
`

**Comment by canihavethisone** [comment]
on CIS hardened systems, /var/tmp is also noexec.  Perhaps another folder such as /usr/local/share/tmp_docker?

**Comment by canihavethisone** [comment]
if users prefer to just allow exec on /tmp and it doesn't conflict with puppet managed hardening, the following works but is yuck
```
  if $compose_defs {
    exec { 'allow exec on /tmp':
      command => 'mount /tmp -o remount,exec',
      unless  => 'mount | grep "on /tmp" | grep -v noexec',
      path    => ['/usr/bin', 'bin']
    }
  }
```

**Comment by chelnak** [comment]
I feel like we should allow the user to decide on the directory that is used to override the `/tmp` directory. We should just give the option to pass in a directory and not prescribe a certain behaviour.

Maybe in the documentation we can indicate that the directory used should not have the `noexec` bit.

**Comment by maltewhiite** [comment]
Experiencing the same thing: 
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/docker_compose: Could not autoload puppet/provider/docker_compose/ruby: Permission denied - /tmp_docker (file: /etc/puppetlabs/code/environments/test/modules/docker/manifests/init.pp, line: 663, column: 8) on node 
```
What version of this puppet-module should I roll back to?

**Comment by canihavethisone** [comment]
v4.1.2 doesn't have this issue.  Alternatively it is doesn't occur on the second puppet run with the latest v4.2.0

**Comment by maltewhiite** [comment]
I only declare "class { 'docker':" and docker::registry and docker::image. No docker::compose at all. Still experienced the error.

**Comment by canihavethisone** [comment]
yep, as noted in the observations above the error appear on first puppet run regardless, however not on subsequent runs and the actual dir creation only occurs if docker_compose is referenced.  I think it is linked to resources not being realized correctly on the first run, but regardless, @chelnak has proposed a more suitable approach moving ahead.

**Comment by chelnak** [comment]
Hey team! I've got a draft PR up with a suggested fix: https://github.com/puppetlabs/puppetlabs-docker/pull/820

It's early days but feedback is welcome.

**Comment by baron1405** [comment]
Please push out a new release ASAP. Thanks!

**Comment by chelnak** [comment]
Hey @baron1405,

We are working on a fix. For now thought, please pin to the previous version if possible.

**Comment by chelnak** [comment]
@canihavethisone We are going to back out the additional changes made to modify the TMPDIR environment variable. In this case, I think the priority is to restore the module to a working state for those that don't/can't pin to a specific versions or for new users of the module.

This is an issue we could still attempt to fix and if you would like to continue it would be great if you could open a new issue for it so we can start discussing the way forward.

Thanks for all of your hard work!

**Comment by baron1405** [comment]
Thanks @chelnak for the quick reply and everyone's work on this!

**Comment by canihavethisone** [comment]
thanks @chelnak .  Good thing is that the idempotency fix for scaling (which was the main intent) remains.

**Comment by chelnak** [comment]
The fix is now in master. I've tested with the following manifest:

```bash
class { 'docker':
  log_driver => 'journald',
}

$compose = "compose_test:
  image: ubuntu:14.04
  command: /bin/sh -c 'while true; do echo hello world; sleep 1; done'
"

file { '/tmp/compose.yml':
  content => $compose
}

class { 'docker::compose':
  ensure => present,
}

docker_compose {'test':
  ensure => present,
  compose_files => [
    '/tmp/compose.yml'
  ],
}
```

snippet of logs

```bash
Info: Checking for compose project test
Debug: Executing: '/usr/local/bin/docker-compose -f /tmp/compose.yml -p test config'
Debug: Executing: '/usr/bin/docker ps --format {{.Label "com.docker.compose.service"}}-{{.Image}} --filter label=com.docker.compose.project=test'
Info: Running compose project test
Debug: Executing: '/usr/local/bin/docker-compose -f /tmp/compose.yml -p test up -d --remove-orphans'
Notice: /Stage[main]/Main/Docker_compose[test]/ensure: created
Debug: /Stage[main]/Main/Docker_compose[test]: The container Class[Main] will propagate my refresh event
Debug: Class[Main]: The container Stage[main] will propagate my refresh event
Debug: Finishing transaction 22400
Debug: Storing state
Debug: Pruned old state cache entries in 0.00 seconds
Debug: Stored state in 0.00 seconds
Notice: Applied catalog in 21.65 seconds
Debug: Applying settings catalog for sections reporting, metrics
Debug: Finishing transaction 28920
Debug: Received report to process from ubuntu2004.localdomain
Debug: Processing report from ubuntu2004.localdomain with processor Puppet::Reports::Store
```

and everything appears to be ok.

We will cut 4.2.1 from this fix.

**Comment by chelnak** [comment]
Hey everyone, version 4.2.1 is now available 👍 

This release removes the additional changes that modified the TMPDIR environment variable.
