### ISSUE TITLE
disable github actions on forks

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-docker#829]
## Describe the Bug
Forks inherit all github actions unnecessarily, conditionals should be set in place to limit actions to the main repository

**Comment by chelnak** [comment]
@vchepkov Which actions did you have issues with?

Depending on the details of the issue, I might close this and create a new one in pdk-templates.

Thanks!

**Comment by chelnak** [comment]
@vchepkov It's been a while since the last response here so I'm going to close this issue.

Given that our actions are managed by the PDK templates I think this is better addressed there.

Thank you!
