### ISSUE TITLE
Support higher docker-compose version, than v1.18

### ISSUE THREAD

**Issue by maltewhiite** [puppetlabs/puppetlabs-docker#839]
## Use Case
A docker-compose version from 2017 is not ideal

## Describe the Solution You Would Like
Support for newer version of docker-compose installed via 
```ruby
class { 'docker::compose':
  ensure => present,
  version => 'latest',
}
```

## Describe Alternatives You've Considered
```ruby
  package { 'docker-compose-plugin':
    ensure  => $docker_version,
    require => Class['docker'],
  }
```
But then `puppet agent -t` says: 
```shell
Error: Could not find a suitable provider for docker_compose
```
So then I use a symlink `/bin/docker-compose -> /usr/libexec/docker/cli-plugins/docker-compose` and now it works
```ruby
  file { '/bin/docker-compose':
    ensure => 'link',
    target => '/usr/libexec/docker/cli-plugins/docker-compose',
  }
```

## Additional Context
We are using CentOS 7. 

```shell
[root@vag:~]# docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```

**Comment by romz169** [comment]
you can tell it to grab a later version via 
version => '1.29.2'

but I don't think it supports version 2 yet

**Comment by chelnak** [comment]
Correct! You can specify the version of compose with the `version` parameter:

```
class {'docker::compose':
  ensure => present,
  version => '1.9.0',
}
```

Also, with regards to v2. The module currently does not support it but this might be something that we consider in the future.

Thanks!
