### ISSUE TITLE
Restaring Changed containers/services

### ISSUE THREAD

**Issue by whitepiratebaku** [puppetlabs/puppetlabs-docker#845]
Hello, we are using docker_compose resource from your module, when we change docker-compose file module does not call docker-compose up -d so we have to add a notify to docker-compose file resource and call exec comand for docker-compose up -d, Normally docker-compose dedects which services changed and do not restart unchanged containers, it would be benefial if you add extra state called latest, which will call docker-compose up -d if  file changed.

**Comment by canihavethisone** [comment]
does this not work for you?
```
file {  '/tmp/docker-compose.yml':
  source => <insert source>,
}

docker_compose { 'test':
  compose_files => ['/tmp/docker-compose.yml'],
  ensure        => present,
  subscribe  => File['/tmp/docker-compose.yml'],
}
```
