### ISSUE TITLE
How to pass '--shm-size' and other arguments to docker::run?

### ISSUE THREAD

**Issue by lidh15** [puppetlabs/puppetlabs-docker#849]
when I use docker run directly, I pass it like `docker run --rm -it --shm-size 32G --privileged --cap-add IPC_LOCK -d my_image /usr/sbin/init`, how should I put these arguments into `docker::run`?

**Comment by lidh15** [comment]
And execute `puppet device --target my_agent --apply my_docker.pp` from server raised `could not run: target device /certificate 'my_agent' not found in /etc/puppetlabs/puppet/device.conf`.
what should I put in that file? I tried those in demo like `type cisco url ...` but it once again said `cannot load such file: -- puppet/util/network_device/cisco/device`.

**Comment by petergmurphy** [comment]
Thank you for reporting this. However, we require more information in order to move forward with this issue. If you would be able to provide:

- your environment setup
- the version of the modules involved
- a manifest to help with reproduction of the issue

The more information you give us the more likely we will be to reproduce and address the issue.

Thanks!

**Comment by lidh15** [comment]
centos7, puppet server 7.8, puppet agent 7.9, puppetlabs stdlib 8.4, puppetlabs docker 4.4
my manifest:
```
# my_docker.pp
class container {
  include::docker
  ::docker::image { 'myimage':
    ensure => 'present',
    image_tag => 'latest',
    requirer => Class['docker'],
  }
  ::docker::run { 'mycontainer':
    image => 'myimage:latest',
    command => '/usr/sbin/init',
    ports => ['8000:80'],
    privileged => true,
    memory_limit => '2g',
    require => Docker::Image['myimage'],
  }
}
include container
```
`puppet device --target my_agent --apply my_docker.pp`

**Comment by petergmurphy** [comment]
To solve your first issue, you can add additional arguments with the `extra_parameters` parameter in `::docker::run`:

```
::docker::run { 'mycontainer':
    image => 'myimage:latest',
    command => '/usr/sbin/init',
    ports => ['8000:80'],
    privileged => true,
    memory_limit => '2g',
    require => Docker::Image['myimage'],
    extra_parameters => ['--rm', '-it', '--shm-size=32G', '--privileged', '--cap-add=IPC_LOCK', '-d', 'my_image', '/usr/sbin/init'],
  }
```

**Comment by petergmurphy** [comment]
For your second issue, I'm not entirely sure what you are trying to achieve.

Would using `puppet apply my_docker.pp` solve this issue for you?

**Comment by lidh15** [comment]
> For your second issue, I'm not entirely sure what you are trying to achieve.
> 
> Would using `puppet apply my_docker.pp` solve this issue for you?

it works when I'm using a singlmachine my. what I want to do is `puppet apply my_docker.pp` on one machine and apply it on another

**Comment by petergmurphy** [comment]
You could use [bolt](https://puppet.com/docs/bolt/latest/bolt.html) to apply the `my_docker.pp` manifest to the other machine.

I think [this](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html#applying-manifest-blocks-from-the-command-line) is what you are looking to do.

**Comment by lidh15** [comment]
ok, thank you
