### ISSUE TITLE
Docker Supported Versions 

### ISSUE THREAD

**Issue by nikzeyn** [puppetlabs/puppetlabs-docker#855]
While deploying docker using puppet, some parts of docs confused me a bit. 

In the beginning part of the doc, it says it is compatible with `Ubuntu 18.04`, `20.04` and `22.04`.

Later on, towards the bottom, it says the module supports: `Ubuntu 14.04`, `16.04`, and `18.04`.
It does not mention `20.04` and `22.04`.

Do I misinterpret the doc or is it something to be updated?

My setup is as follows: 
puppet master is `Ubuntu 20.04`.
puppet agent is `Ubuntu 22.04` (on which I am trying to install docker).
1. docker installs fine if I use: `version => latest`
2. docker install fails if I use: `version => '20.10.16'`

**Comment by smortex** [comment]
Don't trust the README :upside_down_face: ! Ubuntu 14.04, 16.04 are EOL and support for those was removed in v4.2.0 according to CHANGELOG.md.

Only trust the info in metadata.json:
https://github.com/puppetlabs/puppetlabs-docker/blob/88a1f4635eaf35234a215be39cca2f57e73fca74/metadata.json#L35-L42

**Comment by nikzeyn** [comment]
Thanks for your reply. It's clear now.

Yes, true - we can't rely on READMEs all the time 

I'll submit a correction request for the doc then. 

I am still wrestling with it to make it work with the specific version rather than the latest version :)

**Comment by smortex** [comment]
Thanks! Regarding the version number, on debian it's not "just" the version:

```sh-session
root@lambda ~ # puppet resource package docker-ce
package { 'docker-ce':
  ensure   => '5:20.10.17~3-0~debian-bullseye',
  mark     => 'none',
  provider => 'apt',
}
```

Ubuntu may need something in this spirit… `apt-cache policy docker-ce` to the rescue?

**Comment by nikzeyn** [comment]
No problems, the least I could do :)

Re the version number, I tried a few different formats and they didn't work. I have them all in the below question in SO:
https://stackoverflow.com/questions/73629187/installing-specific-docker-version-via-puppet
