### ISSUE TITLE
unable to remove docker services

### ISSUE THREAD

**Issue by RXM307** [puppetlabs/puppetlabs-docker#87]
as per the README I tried adding
    docker::services {'filebeat':
      ensure => 'absent',
      service_name => 'filebeat',
    }

but as it defaults to create = true in services.pp so I tried create => false but it still tries to create

    docker::services {'filebeat':
      create => false,
      ensure => 'absent',
      service_name => 'filebeat',
    }

Exec[Docker service create]/returns: "docker service create" requires at least 1 argument(s).
Exec[Docker service create]/returns: See 'docker service create --help'.
Exec[Docker service create]/returns:
Exec[Docker service create]/returns: Usage:  docker service create [OPTIONS] IMAGE [COMMAND] [ARG...]
Exec[Docker service create]/returns:
Exec[Docker service create]/returns: Create a new service
Error: docker service create --name 'filebeat' returned 1 instead of one of [0]
Exec[Docker service create]/returns: change from notrun to 0 failed: docker service create --name 'filebeat' returned 1 instead of one of [0]

should services.pp be set to
if $create == 'true' {
instead of
if $create {

and the same for
if $update {
and
if $scale {

**Comment by RXM307** [comment]
after further testing it looks like you must specify

  create => false,

I accidentally had the docker::services specified twice in my manifest and it was only hitting the first occurrence.

if this is by design should the README be updated?

**Comment by scotty-c** [comment]
Hi, @RXM307 this is by design, I have updated the README. Thanks for letting us know.
