### ISSUE TITLE
Conflicts between `docker-ce` and `docker-ce-cli`

### ISSUE THREAD

**Issue by deimantastumas** [puppetlabs/puppetlabs-docker#895]
## Describe the Bug
When the older version of docker (anything other than `latest`) is attempted to be installed, Puppet fails to install the packages.

## Expected Behavior
Docker should be properly installed

## Steps to Reproduce
1. Try to install the docker `19.03.9-3.el7` version using `puppetlabs-docker` module
2. Run the puppet 

## Environment
 - Module version: `6.0.2`
 - Platform: `CentOS Linux 7`
 - Puppet agent/server versions: `6.x`

## Additional Context
Looks like the latest version of `docker-ce-cli` is installed as a dependency when installing `docker-ce`. So if we're using the module to install the Docker `19.03.9-3.el7`, it firstly installs the `docker-ce` version `19.03.9-3.el7`, then the latest current version of `docker-ce-cli` is installed as a dependency (currently `23.0.0-1.el7`), then the module tries to install the matching version of `docker-ce-cli` - `19.03.9-3.el7` and it fails with the following error:
```
Error: Could not update: Failed to update to version 19.03.9-3.el7, got version 3:23.0.0-1.el7 instead
Error: /Stage[main]/Docker::Install/Package[docker]/ensure: change from 'purged' to '19.03.9-3.el7' failed: Could not update: Failed to update to version 19.03.9-3.el7, got version 3:23.0.0-1.el7 instead (corrective)
```

**Comment by kenyon** [comment]
See also #865.

**Comment by deimantastumas** [comment]
Hey, https://github.com/puppetlabs/puppetlabs-docker/pull/970 is related and one way or another solves the issue.
