### ISSUE TITLE
Docker module shouldn't manage the EPEL repository (via the epel module)

### ISSUE THREAD

**Issue by tgm4883** [puppetlabs/puppetlabs-docker#9]
This is specifically an issue on RHEL/CentOS < 7 (Specifically, [this code](https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/params.pp#L170) )

## Use cases:

1. A user uses another module to manage the EPEL repository that conflicts with the module that puppetlabs-docker requires. (As discussed in [this thread](https://github.com/stahnma/puppet-module-epel/pull/54#issuecomment-223390720), where the developer states "have whatever is requiring a specific epel module to stop that."
2. A user uses yumrepo to manage EPEL rather than a module (which is what we do because we have a local copy of all the repositories we use)

## Possible fix:
Add a class variable such as 'manage_epel' that can be set to false for users where EPEL is already being managed though some other means.

**Comment by scotty-c** [comment]
We will add this into our next sprint or if you have code already written we are also accepting PR's

**Comment by tgm4883** [comment]
Thanks scotty-c, I don't have code written.

**Comment by LongLiveCHIEF** [comment]
I already have code written for this, but it's only compatible hiera v5. What is this module's intent in terms of  supporting EoL versions of puppet/hiera?

**Comment by scotty-c** [comment]
@LongLiveCHIEF This module will only support the versions we do at Puppet. So puppet 4 and above.
We will still need to support Hiera 3 as most customers have not moved to 5 yet

**Comment by scotty-c** [comment]
This will be fixed in PR #31

**Comment by scotty-c** [comment]
PR #31 is now in master, we have some other changes we would like to add before the next release.
