### ISSUE TITLE
add new fact to support worker/manager tokens

### ISSUE THREAD

**Issue by elimin8r** [puppetlabs/puppetlabs-docker#91]

**Comment by scotty-c** [comment]
Hi @elimin8r we won't be adding this functionality as it poses a security concern you can get the managers token from a box that should not have access through it through a fact.

**Comment by elimin8r** [comment]
Thats fine. Can you update the docs as the best practice to safeguarding
the tokens then. Right now you indicate to place them in the manifest as if
they weren't sensitive.
