### ISSUE TITLE
No IPv6 support

### ISSUE THREAD

**Issue by CAPSLOCK2000** [puppetlabs/puppetlabs-docker#92]
The Docker class doesn't support the IPv6-options to dockerd, such as --ipv6, --fixed-cidr-v6 and  --default-gateway-v6 . Fortunately the extra_parameters option provides a workaround. It would be nicer to configure IPv6 in the same place as IPv4. As fixed_cidr and default_gateway are supported I think the IPv6 equivalents should be added as well.

**Comment by davejrt** [comment]
Hi

Thanks for bringing this up. We will look into it and work on getting it into an upcoming release otherwise we are more than happy to accept community PR's

**Comment by htj** [comment]
+1 for this.

If the docker host has v6, the source ip of an incoming request will be re-written to the gateway of the docker network, which is not really what one wants.

**Comment by davejrt** [comment]
We have a ticket in our backlog that will be actioned in this sprint or next.

**Comment by davejrt** [comment]
This functionality was added in PR #181
