### ISSUE TITLE
No Compose v.3 support

### ISSUE THREAD

**Issue by gettek** [puppetlabs/puppetlabs-docker#94]
Can we please add support for [Docker-Compose File Version 3.0](https://docs.docker.com/compose/compose-file/) and above?

`Error: Execution of '/usr/local/bin/docker-compose -f /media/data/docker-compose.yml up -d' returned 1: Version in "/media/data/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the 'services' key, or omit the 'version' key and place your service definitions at the root of the file to use version 1.`

The [latest release](https://github.com/docker/compose/releases) is backwards compatible

**Comment by scotty-c** [comment]
@SuDT We have compose v3 support in stacks. What are you trying to deploy?
For reference here is the official Docker docs https://docs.docker.com/engine/swarm/stack-deploy/

**Comment by SuDT** [comment]
In instances without swarm is using stack the recommended method? Previously I've used docker_compose (with deprecated module _docker_platform_) as below
```
class { '::docker':
}
class { '::docker::compose':
    ensure => present,
}
docker_compose { '/usr/local/docker-compose.yml':
  ensure  => present,
  require => File['/usr/local/docker-compose.yml']
}
```
It's only when switching to the new Puppet module coupled with compose.v3 that I face issues. This brings me to point out I had to specificity the docker version manually (as below) because when ran against Ubuntu 16.04 simply adding `include 'docker'` to the manifest failed with APT repository errors ("was unable to locate package name docker-ce")
```
  case $facts['os']['name'] {
    /^(Ubuntu)$/:  {
      $dockerversion = '17.12.0~ce-0~ubuntu'
    }    
    /^(Debian)$/:  {
      $dockerversion = '17.12.0~ce-0~debian'
    }
    /^(RHEL|CentOS)$/:  {
      $dockerversion = '17.12.0.ce-1.el7.centos'
    }
  }
  class { 'docker':
    version => $dockerversion,
  }
  docker::stack { 'my_app':
    ensure  => present,
    stack_name => 'my_app',
    compose_file => "/usr/local/docker-compose.yml",
    require => [Class['docker'], File['/usr/local/docker-compose.yaml']],
  }
```
Perhaps there's some config issues on the box I'm using but just wanted point these out. Also applying the catalogue hangs for hours on Docker install, I'll try again on a fresh machine and update.

``` /opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/puppet agent -tv
├─ /opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/puppet agent -tv
├─ /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install docker-ce=17.12.0~ce-0~ubuntu
│  └─ /usr/bin/dpkg --force-confold --status-fd 42 --configure docker-ce:amd64
│     └─ /bin/sh /var/lib/dpkg/info/docker-ce.postinst configure
│        └─ /bin/sh /usr/sbin/invoke-rc.d docker start
│           └─ systemctl start docker.service
├─ debconf-communi
└─ debconf-communi
```

**Comment by davejrt** [comment]
Hi @SuDT 

I've just tested using `include docker` on the puppetlabs ubuntu 16.04 vagrant box locally without issue. 

```
==> node-01: Info: /Stage[main]/Docker::Service/File[/etc/default/docker]: Filebucketed /etc/default/docker to puppet with sum 82d6a44e99db1a3b74f7835e4f5e1b01
==> node-01: Notice: /Stage[main]/Docker::Service/File[/etc/default/docker]/content: content changed '{md5}82d6a44e99db1a3b74f7835e4f5e1b01' to '{md5}9b9e22c51d98b2602162864ad36aeb52'
==> node-01: Info: /Stage[main]/Docker::Service/File[/etc/default/docker]: Scheduling refresh of Service[docker]
==> node-01: Debug: /Stage[main]/Docker::Service/File[/etc/default/docker]: The container Class[Docker::Service] will propagate my refresh event
==> node-01: Debug: Executing: '/bin/systemctl is-active docker'
==> node-01: Debug: Executing: '/bin/systemctl is-enabled docker'
==> node-01: Debug: Executing: '/bin/systemctl is-active docker'
==> node-01: Debug: Executing: '/bin/systemctl restart docker'
==> node-01: Notice: /Stage[main]/Docker::Service/Service[docker]: Triggered 'refresh' from 2 events
==> node-01: Debug: /Stage[main]/Docker::Service/Service[docker]: The container Class[Docker::Service] will propagate my refresh event
==> node-01: Debug: Class[Docker::Service]: The container Stage[main] will propagate my refresh event
==> node-01: Debug: Class[Docker::Service]: The container Class[Docker] will propagate my refresh event
==> node-01: Debug: Class[Docker]: The container Stage[main] will propagate my refresh event
==> node-01: Debug: Finishing transaction 40742360
==> node-01: Debug: Storing state
==> node-01: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> node-01: Debug: Stored state in 0.01 seconds
==> node-01: Notice: Applied catalog in 137.83 seconds
```

Are you specifying a version of compose when you're trying to install it? The docker module, will by default install v 1.9.0 which is not compatible with compose v3. You need compose 1.10.0 or later.

**Comment by SuDT** [comment]
Thank you for the update @davejrt 

This seems to be a docker upgrade from v1.12 to v17.0 issue,
```
apt upgrade
└─ /usr/bin/dpkg --status-fd 42 --configure docker-ce:amd64 grub-common:amd64 grub2-common:amd64 grub-pc-bin:amd64 grub-pc:amd64 li
   └─ /bin/sh /var/lib/dpkg/info/docker-ce.postinst configure
      └─ /bin/sh /usr/sbin/invoke-rc.d docker start
         └─ systemctl --job-mode=ignore-dependencies start docker.service
            └─ /bin/systemd-tty-ask-password-agent --watch
```

I'll experiment with the compose manifest setting you provided once I find a fix.

**Comment by gettek** [comment]
So got the latest Docker and Compose versions working.

I still feel that Compose version 3 is not fully supported via this module as Puppet has trouble picking up my [.env file](https://docs.docker.com/compose/environment-variables/) but does pick it up after manual `docker-compose up -d` run

```
Info: Running compose project 1
Error: Execution of '/usr/local/bin/docker-compose -f /media/data/elk/cluster/1/docker-compose.yml up -d --remove-orphans' returned 1: The ELASTIC_PASSWORD variable is not set. Defaulting to a blank string.
The ELASTIC_HOST_NAME variable is not set. Defaulting to a blank string.
The ELASTIC_HOST_IP variable is not set. Defaulting to a blank string.
The ELASTIC_CLUSTER variable is not set. Defaulting to a blank string.
The TAG variable is not set. Defaulting to a blank string.
no such image: docker.elastic.co/elasticsearch/elasticsearch:: invalid reference format
Error: /Stage[main]/Profiles::Monitoring/Docker_compose[/media/data/elk/cluster/1/docker-compose.yml]/ensure: change from absent to present failed: Execution of '/usr/local/bin/docker-compose -f /media/data/elk/cluster/1/docker-compose.yml up -d --remove-orphans' returned 1: The ELASTIC_PASSWORD variable is not set. Defaulting to a blank string.
The ELASTIC_HOST_NAME variable is not set. Defaulting to a blank string.
The ELASTIC_HOST_IP variable is not set. Defaulting to a blank string.
The ELASTIC_CLUSTER variable is not set. Defaulting to a blank string.
The TAG variable is not set. Defaulting to a blank string.
no such image: docker.elastic.co/elasticsearch/elasticsearch:: invalid reference format
```
Am I missing something here? Is there a way to define compose env variables via the manifest such as...
```
class { '::docker': }
class {'::docker::compose':
  ensure => present,
  version => '1.18.0',
}
docker_compose { "${elasticnode}/docker-compose.yml":
  ensure => present,
  env              => ['FOO=BAR', 'FOO2=BAR2'],
  env_file         => ['/etc/foo', '/etc/bar'],
  scale  => {
    'elasticsearch' => 1,
    'kibana' => 1,
    'logstash' => 1,
    'nginx' => 1,
  },
}
```

**Comment by davejrt** [comment]
@gettek if you're returning a fact and assigning it to a variable inside your compose file, would it not be an acceptable pattern to have the fact in your erb or epp template?

IE:

```
version: '3'
services:
  api:
    image: 'elastic'
    environment:
     - ELASTIC_HOST_IP=<%=  @ipaddress %>
```

**Comment by gettek** [comment]
Thank you @davejrt that will work, 

Unfortunately I'll need to update my PuppetServer to take advantage of EPP as I'm still on 2.8 :-1: 

Despite this I still think its useful to have the option to specify .env paths for compose v3, as you can with [containers](https://forge.puppet.com/puppetlabs/docker#containers)

Thanks all

**Comment by davejrt** [comment]
@gettek Glad that's helped out. I agree that's a nice to have feature and definitely something we can consider on the roadmap for an upcoming release.
